{
 "title": "Home",
 "description": "Overview of all endpoints",
 "time": { "from": "2024-08-05T09:33:58.000Z", "to": "2024-08-05T10:36:05.000Z" },
 "templating": {
  "list": [
   { "name": "runid", "label": "Run", "query": "SELECT id FROM runs" },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SELECT DISTINCT path FROM requests WHERE runid = $runid ORDER BY path ASC"
   }
  ]
 },
 "panels": [
  {
   "title": "Status codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "queryText": "SELECT CAST(status as TEXT), COUNT(*) as 'Count'\r\nFROM responses LEFT JOIN requests ON responses.reqid = requests.id \r\nWHERE runid = $runid AND path IN (${endpoint:sqlstring})\r\nGROUP BY status",
     "rawQueryText": "SELECT CAST(status as TEXT), COUNT(*) as 'Count'\r\nFROM responses LEFT JOIN requests ON responses.reqid = requests.id \r\nWHERE runid = $runid AND path IN (${endpoint:sqlstring})\r\nGROUP BY status",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Number of requests per path",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n    path as metric,\n    count(1) filter(where status BETWEEN 400 AND 499) as \"4xx\",\n    count(1) filter(where status BETWEEN 500 AND 599) as \"5xx\",\n    count(1) filter(where status BETWEEN 200 AND 299) as \"2xx\",\n    count(1) filter(where status NOT BETWEEN 400 AND 599 AND status NOT BETWEEN 200 AND 299) as other\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path",
     "rawQueryText": "SELECT \n    path as metric,\n    count(1) filter(where status BETWEEN 400 AND 499) as \"4xx\",\n    count(1) filter(where status BETWEEN 500 AND 599) as \"5xx\",\n    count(1) filter(where status BETWEEN 200 AND 299) as \"2xx\",\n    count(1) filter(where status NOT BETWEEN 400 AND 599 AND status NOT BETWEEN 200 AND 299) as other\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time,\n  100.0 * endpoint_coverage / endpoint_coverage_total AS \"Endpoint Coverage (%)\",\n  100.0 * line_coverage / line_coverage_total AS \"Line Coverage (%)\"\nFROM\n  coverage\nWHERE\n  runid = \"$runid\"\n",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time,\n  100.0 * endpoint_coverage / endpoint_coverage_total AS \"Endpoint Coverage (%)\",\n  100.0 * line_coverage / line_coverage_total AS \"Line Coverage (%)\"\nFROM\n  coverage\nWHERE\n  runid = \"$runid\"\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "All Status Codes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "queryText": "SELECT \n    path as path,\n    CAST(status AS TEXT) as status,\n    count(1) as count\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path, status",
     "rawQueryText": "SELECT \n    path as path,\n    CAST(status AS TEXT) as status,\n    count(1) as count\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path, status",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}