version: '3.8'
services:
  vampi-restler:
    image: localhost:5000/vampi-vulnerable-restler:latest
    environment:
      - vulnerable=1
    ports:
      - "5012:5000"
    networks:
      - cicd_network
    deploy:
      placement:
        constraints:
          - node.labels.fuzzer == restler
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - /var/lib/docker:/var/lib/docker:rw

  vampi-wuppiefuzz:
    image: localhost:5000/vampi-vulnerable-wuppiefuzz:latest
    environment:
      - vulnerable=1
    ports:
      - "5022:5000"
    networks:
      - cicd_network
    deploy:
      placement:
        constraints:
          - node.labels.fuzzer == wuppiefuzz
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - /var/lib/docker:/var/lib/docker:rw

  vampi-evomaster:
    image: localhost:5000/vampi-vulnerable-evomaster:latest
    environment:
      - vulnerable=1
    ports:
      - "5032:5000"
    networks:
      - cicd_network
    deploy:
      placement:
        constraints:
          - node.labels.fuzzer == evomaster
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - /var/lib/docker:/var/lib/docker:rw

networks:
  cicd_network:
    external: true
    name: cicd_network
