version: '3'

services:
  api:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - SMTP_USER=${SMTP_USER:-dummy_user}
      - SMTP_PASS=${SMTP_PASS:-dummy_pass}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-587}
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  grafana-dashboard:
    image: grafana/grafana-enterprise
    container_name: grafana-dashboard
    ports:
      - "3002:3002"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - ./reports/grafana/report.db:/var/lib/grafana/datasources/report.db
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
