version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    user: "${MY_UID}:${MY_GID}"
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - wuppycicd_network
    volumes:
      - ./reports:/var/lib/grafana/data
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-sqlite-datasource
networks:
  wuppycicd_network:
    external: true
