version: '3.8'

services:
  api:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://db/vulnerable-rest-api
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
    command: ["sh", "docker-entrypoint.sh"]
    depends_on:
      - db
    networks:
      - cicd_network

  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cicd_network

networks:
  cicd_network:
    driver: bridge

volumes:
  mongodb_data:   
    name: mongodb_data   