version: "3.8"

services:
  grafana-dashboard:
    image: custom-grafana
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./reports:/var/lib/grafana/reports
      - ./triaged_reports:/var/lib/grafana/triaged_reports
      - ./provisioning/dashboards:/var/lib/grafana/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
    networks:
      default:
        name: wuppycicd_network

networks:
  default:
    external: true
