version: '3.8'

services:
  grafana-dashboard:
    image: custom-grafana
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning/:/etc/grafana/provisioning/
      - ./reports/:/var/lib/grafana/reports/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    networks:
      - wuppycicd_network

networks:
  wuppycicd_network:
    name: wuppycicd_network
