version: '3.8'

services:
  vampi:
    image: erev0s/vampi:latest
    container_name: vampi
    ports:
      - "5000:5000"
    environment:
      - vulnerable=1
    networks:
      - vampi_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  vampi_network:
    name: vampi_network