version: '3.8'

services:
  dvapi:
    build:
      context: ./DVAPI
      dockerfile: Dockerfile
    container_name: dvapi
    ports:
      - "3000:3000"
    networks:
      - fuzzing-network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  fuzzing-network:
    name: fuzzing-network