version: '3'

services:
  api:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - SMTP_USER=${SMTP_USER:-dummy_user}
      - SMTP_PASS=${SMTP_PASS:-dummy_pass}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-587}
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
