version: '3.8'

services:
  wuppiefuzz:
    build:
      context: .
      dockerfile: Dockerfile.wuppiefuzz
    environment:
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - cicd_network
    volumes:
      - ./reports:/wuppiefuzz/reports

networks:
  cicd_network:
    external: true
