# Use the official Rust image as the base
FROM rust:latest

WORKDIR /wuppiefuzz

# Copy the source code
COPY . .

# Install dependencies
RUN apt-get update && apt-get install -y pkg-config libssl-dev

# Build the application
RUN cargo build --release

# Set the entrypoint
ENTRYPOINT ["./target/release/wuppiefuzz"]
