name: Run EvoMaster
description: Run EvoMaster against VAmPI

inputs:
  time_budget:
    description: Time budget in minutes
    required: true

runs:
  using: composite
  steps:
    - name: Setup EvoMaster Environment
      shell: bash
      run: |
        mkdir -p workspace/evomaster/output workspace/evomaster/config
        docker cp vampi-evomaster:/vampi/openapi_specs/openapi3.yml workspace/evomaster/openapi3.yml

    - name: Build EvoMaster Image
      shell: bash
      run: |
        docker build -t evomaster:latest \
          --cache-from evomaster:latest \
          -f services/evomaster/Dockerfile.evomaster services/evomaster

    - name: Run EvoMaster
      shell: bash
      run: |
        docker run --rm \
          --network evomaster_network \
          -v $PWD/workspace/evomaster/output:/results \
          -v $PWD/workspace/evomaster/openapi3.yml:/evomaster/openapi3.yml:ro \
          -e SPEC_PATH=/evomaster/openapi3.yml \
          -e OUTPUT_DIR=/results \
          -e TARGET_URL=http://vampi-evomaster:5000 \
          -e TIME_BUDGET=${{ inputs.time_budget }}m \
          evomaster:latest
