apiVersion: apps/v1
kind: Deployment
metadata:
  name: vampi-evomaster
  namespace: fuzzing-system
  labels:
    app: vampi-evomaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vampi-evomaster
  template:
    metadata:
      labels:
        app: vampi-evomaster
    spec:
      initContainers:
      - name: wait-for-dns
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup kubernetes.default; do echo waiting for DNS; sleep 2; done;']
      containers:
      - name: vampi-evomaster
        image: vampi-vulnerable-evomaster:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: vulnerable
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vampi-evomaster
  namespace: fuzzing-system
spec:
  selector:
    app: vampi-evomaster
  ports:
  - port: 5032
    targetPort: 5000
  type: NodePort
