apiVersion: apps/v1
kind: Deployment
metadata:
  name: vampi-evomaster
  namespace: fuzzing-system
  labels:
    app: vampi-evomaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vampi-evomaster
  template:
    metadata:
      labels:
        app: vampi-evomaster
    spec:
      containers:
      - name: vampi-evomaster
        image: vampi-vulnerable-evomaster:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: vulnerable
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: vampi-evomaster
  namespace: fuzzing-system
spec:
  selector:
    app: vampi-evomaster
  ports:
  - port: 5032
    targetPort: 5000
  type: NodePort
