name: Run RESTler Fuzzing
description: Run RESTler fuzzing against VAmPI

inputs:
  base_dir:
    description: Base directory for workspace
    required: true
  fuzz_lean_time_budget:
    description: Time budget for fuzz lean phase
    required: true
  fuzz_time_budget:
    description: Time budget for fuzz phase
    required: true

runs:
  using: composite
  steps:
    - name: Setup RESTler Environment
      working-directory: ${{ inputs.base_dir }}/workspace/restler
      shell: bash
      run: mkdir -p output config Compile restlerConfig examples Test FuzzLean Fuzz

    - name: Copy RESTler Config Files
      working-directory: ${{ inputs.base_dir }}/workspace/restler
      shell: bash
      run: |
        cp ../../services/restler/config/config.json config/
        cp ../../services/restler/config/dict.json config/
        cp ../../services/restler/config/engine_settings.json config/
        cp ../../services/restler/config/entrypoint.sh config/
        cp ../../services/restler/docker-compose.restler.yml .
        cp ../../services/restler/Dockerfile.restler .
        docker cp vampi-restler:/vampi/openapi_specs/openapi3.yml openapi3.yml
        chmod -R 755 .

    - name: Build RESTler Image
      working-directory: ${{ inputs.base_dir }}/workspace/restler
      shell: bash
      run: docker build -t restler-fuzzer:latest --cache-from restler-fuzzer:latest -f Dockerfile.restler .

    - name: Run RESTler Fuzzing
      working-directory: ${{ inputs.base_dir }}/workspace/restler
      env:
        TARGET_PORT: '5000'
        TARGET_HOST: vampi-restler
        RUN_FUZZ_LEAN: 'true'
        RUN_FUZZ: 'true'
        FUZZ_LEAN_TIME_BUDGET: ${{ inputs.fuzz_lean_time_budget }}
        FUZZ_TIME_BUDGET: ${{ inputs.fuzz_time_budget }}
      shell: bash
      run: |
        docker run --rm --network restler_network \
          -v $PWD/output:/workspace/output \
          -v $PWD/openapi3.yml:/workspace/openapi3.yml:ro \
          -v $PWD/config:/workspace/config:ro \
          -v $PWD/Compile:/workspace/Compile \
          -v $PWD/restlerConfig:/workspace/restlerConfig \
          -v $PWD/examples:/workspace/examples \
          -v $PWD/Test:/workspace/Test \
          -v $PWD/FuzzLean:/workspace/FuzzLean \
          -v $PWD/Fuzz:/workspace/Fuzz \
          -e RESTLER_TELEMETRY_OPTOUT=1 \
          -e TARGET_IP=${TARGET_HOST} \
          -e TARGET_PORT=${TARGET_PORT} \
          -e RUN_FUZZ_LEAN=${RUN_FUZZ_LEAN} \
          -e FUZZ_LEAN_TIME_BUDGET=${FUZZ_LEAN_TIME_BUDGET} \
          -e RUN_FUZZ=${RUN_FUZZ} \
          -e FUZZ_TIME_BUDGET=${FUZZ_TIME_BUDGET} \
          restler-fuzzer:latest
