version: '3.8'

services:
  schemathesis:
    build:
      context: .
      dockerfile: Dockerfile.schemathesis
    container_name: schemathesis
    volumes:
      - ./output:/app/output
      - ${SWAGGER_FILE:-../targets/vampi/openapi_specs/openapi3.yml}:/app/swagger.yml:ro
    environment:
      TARGET_HOST: ${TARGET_HOST:-localhost}
      TARGET_PORT: ${TARGET_PORT:-3000}
      TARGET_SCHEMA: ${TARGET_SCHEMA:-http}
      TARGET_SWAGGER_PATH: ${TARGET_SWAGGER_PATH:-/swagger.json}
    command: >
      st run
      --base-url ${TARGET_SCHEMA:-http}://${TARGET_HOST:-localhost}:${TARGET_PORT:-3000}
      --checks all
      --stateful=links
      --workers=4
      --report
      --report-file /app/output/report.html
      --show-errors-tracebacks
      --validate-schema
      /app/swagger.yml
    networks:
      - ${TARGET_NAME:-target}_network

networks:
  vampi_network:
    name: vampi_network
    external: true
  juiceshop_network:
    name: juiceshop_network
    external: true
  dvapi_network:
    name: dvapi_network
    external: true
