version: '3.8'

x-target-env: &target-env
  TARGET_HOST: ${TARGET_HOST:-localhost}
  TARGET_PORT: ${TARGET_PORT:-3000}
  TARGET_SCHEMA: ${TARGET_SCHEMA:-http}
  TARGET_SWAGGER_PATH: ${TARGET_SWAGGER_PATH:-/swagger.json}

services:
  schemathesis:
    build:
      context: .
      dockerfile: Dockerfile.schemathesis
    container_name: schemathesis
    volumes:
      - ./output:/app/output
      - ${SWAGGER_FILE:-../targets/vampi/openapi_specs/openapi3.yml}:/app/swagger.yml:ro
    environment:
      <<: *target-env
      FUZZING_DURATION: ${FUZZING_DURATION:-1h}
      REQUESTS_PER_MINUTE: ${REQUESTS_PER_MINUTE:-60}
    command: >
      st run --base-url ${TARGET_SCHEMA:-http}://${TARGET_HOST:-localhost}:${TARGET_PORT:-3000}
      --checks all
      --report
      --report-file /app/output/report.html
      /app/swagger.yml
    networks:
      - fuzzing-network
    depends_on:
      target:
        condition: service_healthy

  target:
    image: ${TARGET_IMAGE}
    container_name: ${TARGET_NAME:-target-app}
    ports:
      - "${TARGET_PORT:-3000}:${TARGET_PORT:-3000}"
    environment:
      <<: *target-env
    networks:
      - fuzzing-network
    healthcheck:
      test: ${HEALTH_CHECK:-["CMD", "curl", "-f", "http://localhost:3000"]}
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  fuzzing-network:
    name: fuzzing-network
    external: true
