name: Process Fuzzing Results
description: Process and summarize fuzzing results from multiple fuzzers

runs:
  using: composite
  steps:
    - name: Initialize Summary
      shell: bash
      run: |
        mkdir -p summary
        cd summary
        echo "# Fuzzing Results Summary" > summary.md
        echo "Generated on $(date)" >> summary.md
        echo "" >> summary.md

    - name: Process RESTler Results
      id: restler
      shell: bash
      run: |
        cd summary
        echo "## RESTler Results" >> summary.md
        if [ -d "restler-results" ]; then
          for PHASE in Test FuzzLean Fuzz; do
            if [ -f "restler-results/$PHASE/RestlerResults/logs/main.txt" ]; then
              echo "### $PHASE Phase" >> summary.md
              echo '```' >> summary.md
              awk '/Found bugs:/{p=1;print;next} /Task/ && p{p=0} p{print}' "restler-results/$PHASE/RestlerResults/logs/main.txt" >> summary.md
              echo '```' >> summary.md
              if grep -q "Found bugs: 1" "restler-results/$PHASE/RestlerResults/logs/main.txt"; then
                echo "critical=true" >> $GITHUB_OUTPUT
              fi
            fi
          done
        else
          echo "No results found for RESTler" >> summary.md
        fi

    - name: Process WuppieFuzz Results
      id: wuppiefuzz
      shell: bash
      run: |
        cd summary
        echo "## WuppieFuzz Results" >> summary.md
        if [ -d "wuppiefuzz-results" ]; then
          echo '```json' >> summary.md
          if [ -f "wuppiefuzz-results/findings.json" ]; then
            cat "wuppiefuzz-results/findings.json" | jq -r '.[] | select(.type=="finding") | {description: .description, route: .route, payload: .payload}' >> summary.md
            if cat "wuppiefuzz-results/findings.json" | jq -e '.[] | select(.type=="finding" and .severity=="high")' > /dev/null; then
              echo "critical=true" >> $GITHUB_OUTPUT
            fi
          fi
          echo '```' >> summary.md
        else
          echo "No results found for WuppieFuzz" >> summary.md
        fi

    - name: Process EvoMaster Results
      id: evomaster
      shell: bash
      run: |
        cd summary
        echo "## EvoMaster Results" >> summary.md
        if [ -d "evomaster-results" ]; then
          echo "### Statistics" >> summary.md
          echo '```' >> summary.md
          if [ -f "evomaster-results/statistics.csv" ]; then
            cat "evomaster-results/statistics.csv" >> summary.md
          fi
          echo '```' >> summary.md
          echo "### Coverage Report" >> summary.md
          echo '```' >> summary.md
          if [ -f "evomaster-results/coverage_report.txt" ]; then
            cat "evomaster-results/coverage_report.txt" >> summary.md
          fi
          echo '```' >> summary.md
        else
          echo "No results found for EvoMaster" >> summary.md
        fi

    - name: Set Critical Findings
      id: process-results
      shell: bash
      run: |
        if [ "${{ steps.restler.outputs.critical }}" = "true" ] || [ "${{ steps.wuppiefuzz.outputs.critical }}" = "true" ]; then
          echo "critical_findings=1" >> $GITHUB_OUTPUT
        else
          echo "critical_findings=0" >> $GITHUB_OUTPUT
        fi
