openapi: '3.0.0'
info:
  title: Vulnerable REST API
  version: '1.0.0'
servers:
  - url: http://localhost:3001
    description: Local server
paths:
  /users:
    get:
      summary: Retrieve a list of users
      responses:
        '200':
          description: A list of users
  /users/{id}:
    get:
      summary: Retrieve a single user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single user
