#!/usr/bin/env python

import json
import unittest
import requests
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *


#  This file was automatically generated by EvoMaster on 2025-02-19T13:47:21.524353Z[Etc/UTC]
#  
#  The generated test suite contains 1 tests
#  
#  Covered targets: 3
#  
#  Used time: 0h 1m 19s
#  
#  Needed budget for current results: 72%
#  
#  This file contains test cases that represent failed calls, but not indicative of faults.
class EvoMaster_others_Test(unittest.TestCase):

    
    baseUrlOfSut = "http://localhost:5000"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (400) POST:/users/v1/login
    @timeout_decorator.timeout(60)
    def test_0(self):
        
        headers = {}
        headers["content-type"] = "application/json"
        body = {}
        body = " {} "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/users/v1/login",
                    headers=headers, data=body)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["status"] == "fail"
        assert res_0.json()["message"] == "'username' is a required property"


if __name__ == '__main__':
    unittest.main()
