FROM rust:1.68 as builder
ARG OPENAPI_SPEC=api.yml

WORKDIR /app
COPY . .
COPY services/vampi/openapi_specs/${OPENAPI_SPEC} /app/api.yml
RUN cargo build --release

# Final image
FROM debian:bullseye-slim
COPY --from=builder /app/target/release/wuppiefuzz /usr/local/bin/
COPY services/vampi/openapi_specs/${OPENAPI_SPEC} /app/api.yml

ENTRYPOINT ["wuppiefuzz"]