version: '3.8'

services:
  wuppiefuzz:
    build:
      context: .
      dockerfile: Dockerfile.wuppiefuzz
    container_name: wuppiefuzz
    environment:
      VAMPI_WUPPIEFUZZ_URL: ${VAMPI_WUPPIEFUZZ_URL}
    volumes:
      - ./reports:/wuppiefuzz/reports
      - ../../openapi/openapi3.yml:/workspace/openapi3.yml:ro
    networks:
      - wuppiefuzz_network

networks:
  wuppiefuzz_network:
    name: wuppiefuzz_network
    driver: bridge
