# Builder stage using modern Rust version
FROM rust:1.77 AS builder

ARG WUPPIEFUZZ_COMMIT=main

# Clone and prepare repository
RUN git clone https://github.com/TNO-S3/WuppieFuzz.git /wuppiefuzz && \
    cd /wuppiefuzz && \
    git checkout $WUPPIEFUZZ_COMMIT

# Install build dependencies
RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*

# Build application
WORKDIR /wuppiefuzz
RUN cargo update && \
    cargo build --release

# Final stage
FROM debian:bookworm-slim

WORKDIR /wuppiefuzz
COPY --from=builder /wuppiefuzz/target/release/wuppiefuzz /usr/local/bin/
ENTRYPOINT ["wuppiefuzz"]