version: '3.8'

services:
  wuppiefuzz:
    image: rust:latest
    volumes:
      - ${BASE_DIR}/wuppiefuzz_bin:/app
      - ${BASE_DIR}/services/vampi/openapi_specs:/specs
      - ${BASE_DIR}/wuppiefuzz_workspace:/workspace
    command: >
      sh -c "./wuppiefuzz fuzz
      --openapi-spec=/specs/wuppiefuzz.openapi3.yml
      --report-dir=/workspace/reports
      --timeout=60"
    networks:
      - wuppiefuzz_network

networks:
  wuppiefuzz_network:
    external: true
    name: wuppiefuzz_network_${NETWORK_SUFFIX}