version: '3.8'

services:
  wuppiefuzz:
    build:
      context: .
      dockerfile: Dockerfile.wuppiefuzz
    environment:
      TARGET_HOST: ${TARGET_HOST:-vampi-wuppiefuzz}
      TARGET_PORT: ${TARGET_PORT:-5002}
    volumes:
      - ${BASE_DIR}/services/vampi/openapi_specs:/specs:ro
      - ${BASE_DIR}/workspace/wuppiefuzz/output:/workspace/output
    command: >-
      sh -c "./wuppiefuzz fuzz
      --openapi-spec=/specs/wuppiefuzz.openapi3.yml
      --target-url=http://$${TARGET_HOST}:$${TARGET_PORT}
      --report-dir=/workspace/output
      --timeout=60"
    networks:
      - default