version: '3.8'

services:
  wuppiefuzz:
    build:
      context: .
      dockerfile: Dockerfile.wuppiefuzz
    environment:
      TARGET_URL: "http://vampi:5000"  # Use service name from network
    volumes:
      - ./reports:/app/reports
      - ../../openapi/openapi3.yml:/app/openapi3.yml:ro  # Match container path
    networks:
      - wuppiefuzz_network

networks:
  wuppiefuzz_network:
    external: true