version: '3.8'

services:
  wuppiefuzz:
    build:
      context: services/wuppiefuzz
      dockerfile: Dockerfile.wuppiefuzz
      args:
        OPENAPI_SPEC: openapi_specs/openapi3.yml
    container_name: wuppiefuzz
    environment:
      VAMPI_WUPPIEFUZZ_URL: ${VAMPI_WUPPIEFUZZ_URL}
      RUST_LOG: info
    volumes:
      - fuzz-results:/wuppiefuzz/reports
    networks:
      - cicd_network
    configs:
      - source: openapi-config
        target: /wuppiefuzz/openapi3.yml

networks:
  cicd_network:
    external: true

volumes:
  fuzz-results:
    external: true

configs:
  openapi-config:
    external: true