version: '3.8'

services:
  wuppiefuzz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wuppiefuzz
    environment:
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      VAMPI_WUPPIEFUZZ_URL: ${VAMPI_WUPPIEFUZZ_URL}
    volumes:
      - ./reports:/wuppiefuzz/reports
      - ../../openapi/openapi3.yml:/workspace/openapi3.yml:ro
    networks:
      - cicd_network

networks:
  cicd_network:
    external: true