version: '3.8'

services:
  evomaster:
    build:
      context: .
      dockerfile: Dockerfile.evomaster
    container_name: evomaster
    environment:
      SPEC_PATH: "/specs/openapi3.yml"
      OUTPUT_DIR: "/evomaster/results"
      TARGET_URL: "http://vampi-vulnerable-evomaster:5000"
      TIME_BUDGET: "3600"
    volumes:
      - ./openapi_evomaster.yml:/specs/openapi3.yml:ro
      - ./evomaster_results:/evomaster/results
    networks:
      - cicd_network

networks:
  cicd_network:
    external: true
