version: '3.8'

services:
  evomaster:
    build:
      context: .
      dockerfile: Dockerfile.evomaster
    volumes:
      - ${BASE_DIR}/workspace/evomaster/output:/evomaster/results
      - ${BASE_DIR}/services/vampi/openapi_specs:/specs:ro
    environment:
      TARGET_HOST: ${TARGET_HOST:-vampi-evomaster}
      TARGET_PORT: ${TARGET_PORT:-5000}
      SPEC_PATH: "/specs/wuppiefuzz.openapi3.yml"
      TARGET_URL: "http://${TARGET_HOST:-vampi-evomaster}:${TARGET_PORT:-5000}"
      TIME_BUDGET: "3600"
    networks:
      - default