version: "3"
services:
  vampi:
    build: ../vampi
    container_name: vampi-evomaster
    ports:
      - 5000:5000
    environment:
      - vulnerable=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - evomaster-net

networks:
  evomaster-net:
    driver: bridge
