version: "3"
services:
  vampi-secure:
    build: ./
    container_name: vampi-secure
    ports:
      - 5001:5000
    environment:
      - vulnerable=0

  vampi-vulnerable:
    build: ./
    container_name: vampi-vulnerable
    environment:
      - vulnerable=1
    networks:
      - cicd_network

networks:
  cicd_network:
    external: true
