version: "3"
services:
  vampi-secure:
    build: ./
    container_name: vampi-secure
    ports:
      - 5001:5000
    environment:
      - vulnerable=0

  vampi-vulnerable-wuppiefuzz:
    build: ./
    container_name: vampi-vulnerable
    environment:
      - vulnerable=1
    networks:
      - cicd_network
    ports:
      - 5002:5000

  vampi-vulnerable-restler:
    build: ./
    container_name: vampi-vulnerable
    environment:
      - vulnerable=1
    networks:
      - cicd_network
    ports: 
      - 5002:5001

networks:
  cicd_network:
    external: true
