version: '3.8'
services:
  vampi-secure:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vampi-secure
    ports:
      - "5001:5000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=0
      - vulnerable=0
    depends_on:
      - mongo
    networks:
      - cicd_network
    healthcheck:
      test: curl -f http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  vampi-vulnerable-restler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vampi-vulnerable-restler
    environment:
      - APP_ENV=development
      - APP_DEBUG=1
      - vulnerable=1
    ports:
      - "${VAMPI_RESTLER_PORT}:5000"
    depends_on:
      - mongo
    networks:
      - cicd_network
    healthcheck:
      test: curl -f http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  vampi-vulnerable-wuppiefuzz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vampi-vulnerable-wuppiefuzz
    environment:
      - APP_ENV=development
      - APP_DEBUG=1
      - vulnerable=1
    ports:
      - "${VAMPI_WUPPIEFUZZ_PORT}:5000"
    depends_on:
      - mongo
    networks:
      - cicd_network
    healthcheck:
      test: curl -f http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mongo:
    image: mongo:4.2
    container_name: vampi-mongo
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cicd_network

networks:
  cicd_network:
    external: true

volumes:
  mongo_data: