services:
  vampi:
    image: ghcr.io/your-repo/vampi:latest
    networks:
      - fuzz-net
    environment:
      - vulnerable=${VULNERABLE:-1}  # Parameterized environment variable
    configs:
      - source: openapi-config
        target: /vampi/openapi_specs/api.yml
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s

configs:
  openapi-config:
    external: true  # Config must be created in Swarm first
    name: openapi-spec

networks:
  fuzz-net:
    external: true
    name: ${DOCKER_NETWORK_NAME:-fuzz-net}