version: '3.8'

services:
  vampi-evomaster:
    image: localhost:5000/vampi-vulnerable-evomaster:latest
    environment:
      - vulnerable=1
    ports:
      - "5032:5000"
    networks:
      - evomaster_network
    deploy:
      placement:
        constraints:
          - node.labels.fuzzer == evomaster

networks:
  evomaster_network:
    external: true
