vampi-vulnerable-evomaster:
  build:
    context: .
    dockerfile: ./Dockerfile
  container_name: vampi-vulnerable-evomaster
  environment:
    - APP_ENV=development
    - APP_DEBUG=1
    - vulnerable=1
  ports:
    - "${VAMPI_EVOMASTER_PORT}:5000"  # Maps host port 5000 to container port 5000
  depends_on:
    mongo:
      condition: service_healthy
  networks:
    - evomaster_network
  healthcheck:
    test: curl -f http://localhost:5000/health || exit 1
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 30s