version: '3.8'

services:
  vampi-evomaster:
    build: .
    container_name: ${CONTAINER_NAME:-vampi-evomaster}
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - vulnerable=1
    networks:
      - default

  vampi-restler:
    build: .
    container_name: ${CONTAINER_NAME:-vampi-restler}
    ports:
      - "${PORT:-5003}:5000"
    environment:
      - vulnerable=1
    networks:
      - default

  vampi-wuppiefuzz:
    build: .
    container_name: ${CONTAINER_NAME:-vampi-wuppiefuzz}
    ports:
      - "${PORT:-5002}:5000"
    environment:
      - vulnerable=1
    networks:
      - default