version: '3.8'

services:
  vampi-restler:
    image: localhost:5000/vampi-vulnerable-restler:latest
    environment:
      - vulnerable=1
    ports:
      - "5012:5000"
    networks:
      - fuzzing_network
    deploy:
      placement:
        constraints:
          - node.labels.fuzzer == restler

networks:
  fuzzing_network:
    external: true
