version: "3"
services:
  vampi-secure:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vampi-secure
    ports:
      - "5001:5000"
    environment:
      - vulnerable=0
      - APP_DEBUG=0

  vampi-vulnerable-restler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vampi-vulnerable-restler
    ports:
      - "5002:5000"
    environment:
      - vulnerable=1
      - APP_DEBUG=0

  vampi-vulnerable-evomaster:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vampi-vulnerable-evomaster
    ports:
      - "5003:5000"
    environment:
      - vulnerable=1
      - APP_DEBUG=0

  mongo:
    image: mongo:4.2
    container_name: vampi-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - cicd_network
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  cicd_network:
    external: true

volumes:
  mongo_data: