services:
 vampi-secure:
  build: ./
  container_name: vampi-secure-${PORT:-5001}
  ports:
   - ${PORT:-5001}:5000
  environment:
   - vulnerable=0
  networks:
   - cicd_network
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:5000/"]
    interval: 5s
    timeout: 3s
    retries: 5
    start_period: 2s
  restart: "no"
  stop_grace_period: 1s

 vampi-vulnerable:
  build: ./
  container_name: vampi-vulnerable-${PORT:-5002}
  ports:
   - ${PORT:-5002}:5000
  environment:
   - vulnerable=1
  networks:
   - cicd_network
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:5000/"]
    interval: 5s
    timeout: 3s
    retries: 5
    start_period: 2s
  restart: "no"
  stop_grace_period: 1s

networks:
  cicd_network:
    external: true
