services:
 vampi-secure:
  build: ./
  container_name: vampi-secure
  ports:
   - ${PORT:-5001}:5000
  environment:
   - vulnerable=0
  networks:
   - cicd_network
  healthcheck:
    test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s

 vampi-vulnerable:
  build: ./
  container_name: vampi-vulnerable
  ports:
   - ${PORT:-5002}:5000
  environment:
   - vulnerable=1
  networks:
   - cicd_network
  healthcheck:
    test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s

networks:
  cicd_network:
    external: true
