services:
  vampi-secure:
    build:
      context: ./
      target: secure
    ports:
      - "${PORT:-5001}:5000"
    environment:
      - vulnerable=0
    networks:
      - cicd_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s
    restart: "no"
    stop_grace_period: 1s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        max_attempts: 3

  vampi-vulnerable:
    build:
      context: ./
      target: vulnerable
    ports:
      - "${PORT:-5002}:5000"
    environment:
      - vulnerable=1
    networks:
      - cicd_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s
    restart: "no"
    stop_grace_period: 1s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  cicd_network:
    external: true
    driver: overlay
    attachable: true
    name: ${DOCKER_NETWORK_NAME:-cicd_network}
