version: "3"
services:
 vampi-secure:
  build: ./
  container_name: vampi-secure
  ports:
   - 5001:5000
  environment:
   - vulnerable=0
  healthcheck:
    test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s

 vampi-vulnerable:
  build: ./
  container_name: vampi-vulnerable
  ports:
   - 5002:5000
  environment:
   - vulnerable=1
  healthcheck:
    test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 5s
