version: '3.8'

services:
  vampi-secure:
    build: .
    container_name: vampi-secure
    ports:
      - "5001:5000"
    environment:
      - vulnerable=0
    networks:
      - vampi_network

  vampi-vulnerable:
    build: .
    container_name: vampi-vulnerable
    ports:
      - "5002:5000"
    environment:
      - vulnerable=1
    networks:
      - vampi_network

networks:
  vampi_network:
    name: vampi_network_${NETWORK_SUFFIX}