version: '3.8'

services:
  api:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://mongo/vulnerable-rest-api
    env_file:
      - ../server/smtp_config.list
    command: ["sh", "docker-entrypoint.sh"]
    depends_on:
      - mongo
    networks:
      - restler_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - restler_network

  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    networks:
      - restler_network
    depends_on:
      - api
    entrypoint: ["sh", "/restler_config/entrypoint.sh"]

networks:
  restler_network:
    name: restler_network
