version: '3'

services:
  api:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - SMTP_USER=${SMTP_USER:-dummy_user}
      - SMTP_PASS=${SMTP_PASS:-dummy_pass}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-587}
    depends_on:
      - mongo
    networks:
      - restler_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - restler_network

  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    volumes:
      - ./restler:/restler_workdir
    networks:
      - restler_network
    depends_on:
      - api
    entrypoint: ["sh", "/restler_config/entrypoint.sh"]

networks:
  restler_network:
    name: restler_network
