version: '3.8'
services:
  restler:
    build:
      context: ./
      dockerfile: Dockerfile.restler
    environment:
      SWAGGER_URL: 'http://host.docker.internal:5000/openapi.yaml'
      RUN_FUZZ_LEAN: 'true'
      FUZZ_LEAN_TIME_BUDGET: '0.01'
      RUN_FUZZ: 'true'
      FUZZ_TIME_BUDGET: '1'
      RESTLER_TELEMETRY_OPTOUT: '1'
    networks:
      - cicd_network
    volumes:
      - ./output:/home/restler/output
      - ./openapi.yaml:/workspace/openapi.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  cicd_network:
    external: true