version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    environment:
      HOST: host.docker.internal
      PORT: 3001
      SWAGGER_URL: http://localhost:3001/openapi.yaml
      RUN_FUZZ_LEAN: "true"
      FUZZ_LEAN_TIME_BUDGET: "0.01"
      RUN_FUZZ: "true"
      FUZZ_TIME_BUDGET: "1"
      RESTLER_TELEMETRY_OPTOUT: "1"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - cicd_network
    volumes:
      - ./output:/home/restler/output

networks:
  cicd_network:
    external: true
