FROM python:3.9-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    apt-transport-https \
    git \
    curl \
    build-essential \
    libssl-dev \
    && wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y dotnet-sdk-6.0 \
    && rm -rf /var/lib/apt/lists/*

# Clone the official Restler repository
RUN git clone https://github.com/microsoft/restler-fuzzer.git /restler

# Install Restler dependencies
WORKDIR /restler
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Build Restler
RUN dotnet build Restler.csproj -c Release

# Set the working directory
WORKDIR /restler

# Copy Restler configuration files and entrypoint
COPY ./restler_config /restler_config
COPY restler_config/entrypoint.sh /restler_config/entrypoint.sh

# Ensure the entrypoint is executable
RUN chmod +x /restler_config/entrypoint.sh && \
    sed -i 's/\r$//g' /restler_config/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/restler_config/entrypoint.sh"]