version: '3.8'
services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    environment:
      RESTLER_TELEMETRY_OPTOUT: "1"
      RUN_FUZZ_LEAN: "true"
      FUZZ_LEAN_TIME_BUDGET: "0.05"
      RUN_FUZZ: "true"
      FUZZ_TIME_BUDGET: "0.25"
    volumes:
      - ./openapi3.yml:/workspace/openapi3.yml:ro
      - ./output:/workspace/output
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cicd_network

networks:
  cicd_network:
    external: true