version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    environment:
      RESTLER_TELEMETRY_OPTOUT: "1"
      RUN_FUZZ_LEAN: "true"
      FUZZ_LEAN_TIME_BUDGET: "0.05"
      RUN_FUZZ: "true"
      FUZZ_TIME_BUDGET: "0.25"
      VAMPI_RESTLER_URL: ${VAMPI_RESTLER_URL}
    volumes:
      - ../VAmPI-master/openapi_specs/openapi3.yml:/workspace/openapi3.yml:ro
      - ./output:/workspace/output
    networks:
      - cicd_network
    depends_on:
      - vampi-vulnerable-restler

networks:
  cicd_network:
    external: true
