version: '3.8'

services:
  restler:
    build:
      context: ./restler
      dockerfile: Dockerfile.restler
    environment:
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      HOST: host.docker.internal
      PORT: '3001'
      SWAGGER_URL: 'http://localhost:3001/openapi.yaml'
      RUN_FUZZ_LEAN: 'true'
      FUZZ_LEAN_TIME_BUDGET: '0.01'
      RUN_FUZZ: 'true'
      FUZZ_TIME_BUDGET: '1'
      RESTLER_TELEMETRY_OPTOUT: '1'
    depends_on:
      - api
    networks:
      - cicd_network
    volumes:
      - ./restler/output:/home/restler/output

networks:
  cicd_network:
    external: true
