version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    volumes:
      - ./output:/RESTler/output
      - ./config:/RESTler/config
      - ${SWAGGER_FILE:-../targets/vampi/openapi_specs/openapi3.yml}:/RESTler/swagger.yml:ro
    environment:
      TARGET_HOST: ${TARGET_HOST:-localhost}
      TARGET_PORT: ${TARGET_PORT:-3000}
      TARGET_SCHEMA: ${TARGET_SCHEMA:-http}
      TARGET_SWAGGER_PATH: ${TARGET_SWAGGER_PATH:-/swagger.json}
      RESTLER_TELEMETRY_OPTOUT: 1
    command: >
      bash -c "
        python ./restler/Restler.py compile --api_spec /RESTler/swagger.yml &&
        python ./restler/Restler.py test --grammar_file ./RestlerGrammar/grammar.py &&
        python ./restler/Restler.py fuzz-lean --grammar_file ./RestlerGrammar/grammar.py --settings /RESTler/config/fuzz-lean-config.json &&
        python ./restler/Restler.py fuzz --grammar_file ./RestlerGrammar/grammar.py --settings /RESTler/config/fuzz-config.json
      "
    networks:
      - ${TARGET_NAME:-target}_network

networks:
  vampi_network:
    name: vampi_network
    external: true
  juiceshop_network:
    name: juiceshop_network
    external: true
  dvapi_network:
    name: dvapi_network
    external: true
