version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    volumes:
      - ./output:/RESTler/output
      - ./config:/RESTler/config
      - ${SWAGGER_FILE:-../targets/vampi/openapi_specs/openapi3.yml}:/RESTler/swagger.yml:ro
    environment:
      TARGET_HOST: ${TARGET_HOST:-localhost}
      TARGET_PORT: ${TARGET_PORT:-3000}
      TARGET_SCHEMA: ${TARGET_SCHEMA:-http}
      TARGET_SWAGGER_PATH: ${TARGET_SWAGGER_PATH:-/swagger.json}
      RESTLER_TELEMETRY_OPTOUT: 1
    entrypoint: /bin/bash
    command: >
      -c "/service/config/entrypoint.sh compile --api_spec /RESTler/swagger.yml &&
          /service/config/entrypoint.sh test --api_spec /RESTler/swagger.yml --time_budget 600 &&
          /service/config/entrypoint.sh fuzz-lean --api_spec /RESTler/swagger.yml --time_budget 1800 &&
          /service/config/entrypoint.sh fuzz --api_spec /RESTler/swagger.yml --time_budget 3600"
    networks:
      - ${TARGET_NAME:-target}_network

networks:
  vampi_network:
    name: vampi_network
    external: true
  juiceshop_network:
    name: juiceshop_network
    external: true
  dvapi_network:
    name: dvapi_network
    external: true
