version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    volumes:
      - ./output:/RESTler/output
      - ./config:/RESTler/config
      - ${SWAGGER_FILE:-../targets/vampi/openapi_specs/openapi3.yml}:/RESTler/swagger.yml:ro
    environment:
      TARGET_HOST: ${TARGET_HOST:-localhost}
      TARGET_PORT: ${TARGET_PORT:-3000}
      TARGET_SCHEMA: ${TARGET_SCHEMA:-http}
      TARGET_SWAGGER_PATH: ${TARGET_SWAGGER_PATH:-/swagger.json}
      RESTLER_TELEMETRY_OPTOUT: 1
    entrypoint: /bin/bash
    command: >
      -c "
      echo 'Step 1: Compile grammar' &&
      dotnet /RESTler/restler/Restler.dll compile --api_spec /RESTler/swagger.yml &&
      echo 'Step 2: Test' &&
      dotnet /RESTler/restler/Restler.dll test --grammar_file Compile/grammar.py --no_ssl --host ${TARGET_HOST} --port ${TARGET_PORT} &&
      echo 'Step 3: Fuzz-Lean' &&
      dotnet /RESTler/restler/Restler.dll fuzz-lean --grammar_file Compile/grammar.py --no_ssl --host ${TARGET_HOST} --port ${TARGET_PORT} &&
      echo 'Step 4: Fuzz' &&
      dotnet /RESTler/restler/Restler.dll fuzz --grammar_file Compile/grammar.py --no_ssl --host ${TARGET_HOST} --port ${TARGET_PORT}
      "
    networks:
      - ${TARGET_NAME:-target}_network

networks:
  vampi_network:
    name: vampi_network
    external: true
  juiceshop_network:
    name: juiceshop_network
    external: true
  dvapi_network:
    name: dvapi_network
    external: true
