version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    environment:
      RESTLER_TELEMETRY_OPTOUT: "1"
      RUN_FUZZ_LEAN: ${RUN_FUZZ_LEAN:-true}
      FUZZ_LEAN_TIME_BUDGET: ${FUZZ_LEAN_TIME_BUDGET:-0.25}
      RUN_FUZZ: ${RUN_FUZZ:-true}
      FUZZ_TIME_BUDGET: ${FUZZ_TIME_BUDGET:-0.75}
      TARGET_IP: ${TARGET_HOST:-vampi}
      TARGET_PORT: ${TARGET_PORT:-5000}
      SWAGGER_URL: "http://${TARGET_HOST:-vampi}:${TARGET_PORT:-5000}/openapi3.yml"
      DEBUG_LEVEL: "debug"
    volumes:
      - ${BASE_DIR:-./workspace/restler}/output:/workspace/output
      - ${BASE_DIR:-./workspace/restler}/Compile:/workspace/Compile
      - ${BASE_DIR:-./workspace/restler}/openapi3.yml:/workspace/openapi3.yml:ro
      - ${BASE_DIR:-./workspace/restler}/config:/workspace/config:ro
      - ${BASE_DIR:-./workspace/restler}/restlerConfig:/workspace/restlerConfig
      - ${BASE_DIR:-./workspace/restler}/examples:/workspace/examples
    networks:
      - ${DOCKER_NETWORK_NAME:-fuzzing_network}

networks:
  ${DOCKER_NETWORK_NAME:-fuzzing_network}:
    external: true
