services:
  vampi:
    image: erev0s/vampi:latest
    container_name: vampi-restler
    ports:
      - "5000:5000"
    environment:
      - vulnerable=1
    networks:
      - restler-net
    command: ["app.py"]  # Use CMD array format to work with ENTRYPOINT

  init-vampi:
    image: curlimages/curl:latest
    depends_on:
      - vampi
    networks:
      - restler-net
    command: ["sh", "-c", "until curl -s http://vampi:5000/createdb; do sleep 2; done"]

  restler:
    build:
      context: ../..
      dockerfile: services/restler/Dockerfile.restler
    depends_on:
      - init-vampi
    volumes:
      - ../../services/vampi/openapi_specs:/specs
      - ./output:/workspace/fuzzing_results
    networks:
      - restler-net
    environment:
      - OPENAPI_SPEC=/specs/openapi3.yml
      - TARGET_URL=http://vampi:5000
      - MODE=all

networks:
  restler-net:
    driver: bridge