version: '3.8'

services:
  vampi:
    build: ../vampi
    container_name: vampi
    ports:
      - "5002:5000"
    environment:
      - vulnerable=1
    volumes:
      - ../vampi/openapi_specs:/app/openapi_specs
    networks:
      - restler-net

  init-vampi:
    image: curlimages/curl:latest
    depends_on:
      - vampi
    networks:
      - restler-net
    command: ["sh", "-c", "until curl -s http://vampi:5000/createdb; do sleep 2; done"]

  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    depends_on:
      - init-vampi
    user: root  # Ensure we have permissions to write to output
    volumes:
      - ./openapi3.yml:/workspace/openapi3.yml:ro
      - ./output:/workspace/output:rw
      - ./config:/service/config:rw
    networks:
      - restler-net
    environment:
      - TARGET_IP=vampi
      - TARGET_PORT=5000
      - VULNERABLE_MODE=1
      - BASE_DIR=/workspace
    command: ["bash", "-c", "/service/config/run-restler.sh"]

networks:
  restler-net:
    driver: bridge
