version: "3.9"
services:
  vampi:
    image: erev0s/vampi:latest
    container_name: vampi-restler
    ports:
      - "5000:5000"
    environment:
      - vulnerable=1
      - tokentimetolive=300
    networks:
      - restler-net
    command: ["app.py"]

  init-vampi:
    image: curlimages/curl:latest
    depends_on:
      - vampi
    networks:
      - restler-net
    command: ["sh", "-c", "until curl -s http://vampi:5000/createdb; do sleep 2; done"]

  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    depends_on:
      - init-vampi
    volumes:
      - ../vampi/openapi_specs/openapi3.yml:/workspace/openapi3.yml:ro
      - ${BASE_DIR}/services/restler/output:/workspace/output:rw
    networks:
      - restler-net
    environment:
      - TARGET_IP=vampi
      - TARGET_PORT=5000
    entrypoint: ["/bin/sh", "-c"]
    command: ["/service/config/entrypoint.sh compile --api_spec=/workspace/openapi3.yml && /service/config/entrypoint.sh fuzz-lean --api_spec=/workspace/openapi3.yml --time_budget=3600"]

networks:
  restler-net:
    driver: bridge
