version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    environment:
      RESTLER_TELEMETRY_OPTOUT: "1"
      TARGET_IP: ${TARGET_HOST:-vampi-restler}
      TARGET_PORT: ${TARGET_PORT:-5003}
    volumes:
      - ${BASE_DIR}/services/vampi/openapi_specs/restler.openapi3.yml:/workspace/spec.yml:ro
      - ${BASE_DIR}/workspace/restler/output:/workspace/output
    networks:
      - default