version: '3.8'

services:
  vampi-secure:
    build: ../vampi
    container_name: vampi-secure
    ports:
      - "5001:5000"
    environment:
      - vulnerable=0
    volumes:
      - ../vampi/openapi_specs:/app/openapi_specs
    networks:
      - restler-net

  vampi-vulnerable:
    build: ../vampi
    container_name: vampi-vulnerable  
    ports:
      - "5002:5000"
    environment:
      - vulnerable=1
    volumes:
      - ../vampi/openapi_specs:/app/openapi_specs
    networks:
      - restler-net

  init-vampi:
    image: curlimages/curl:latest
    depends_on:
      - vampi-vulnerable
    networks:
      - restler-net
    command: ["sh", "-c", "until curl -s http://vampi-vulnerable:5000/createdb; do sleep 2; done"]

  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    depends_on:
      - init-vampi
    volumes:
      - ../vampi/openapi_specs/openapi3.yml:/workspace/openapi3.yml:ro
      - ${BASE_DIR}/services/restler/output:/workspace/output:rw
    networks:
      - restler-net
    environment:
      - TARGET_IP=vampi-vulnerable
      - TARGET_PORT=5000
      - VULNERABLE_MODE=1
    entrypoint: ["/bin/sh", "-c"]
    command: ["/service/config/entrypoint.sh compile --api_spec=/workspace/openapi3.yml && /service/config/entrypoint.sh fuzz-lean --api_spec=/workspace/openapi3.yml --time_budget=3600"]

networks:
  restler-net:
    driver: bridge
