services:
  vampi:
    image: erev0s/vampi:latest
    ports:
      - "5000:5000"
    environment:
      - vulnerable=1
    networks:
      - restler-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      start_period: 40s
      interval: 10s
      timeout: 5s
      retries: 3
  restler:
    build:
      context: ../..
      dockerfile: services/restler/Dockerfile.restler
    depends_on:
      vampi:
        condition: service_healthy
    volumes:
      - ../../services/vampi/openapi_specs:/specs
      - ./output:/workspace/fuzzing_results
    networks:
      - restler-net
    environment:
      - OPENAPI_SPEC=/specs/openapi3.yml
      - TARGET_URL=http://vampi:5000
      - MODE=all  # Run complete mode sequence

networks:
  restler-net:
    driver: bridge