version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    container_name: restler
    environment:
      RESTLER_TELEMETRY_OPTOUT: "1"
      RUN_FUZZ_LEAN: "true"
      FUZZ_LEAN_TIME_BUDGET: "0.05"
      RUN_FUZZ: "true"
      FUZZ_TIME_BUDGET: "0.25"
      TARGET_IP: "vampi-vulnerable"
      TARGET_PORT: "5000"
      SWAGGER_URL: "http://vampi-vulnerable:5000/openapi.yaml"
    volumes:
      - ./:/workspace
      - ./config:/service/config
    networks:
      - cicd_network

networks:
  cicd_network:
    external: true
