version: '3.8'

services:
  vampi:
    image: erev0s/vampi:latest
    container_name: vampi-restler
    ports:
      - "5000:5000"
    environment:
      - vulnerable=1
    networks:
      - restler-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["app.py"]  # Use CMD array format to work with ENTRYPOINT

  init-vampi:
    image: curlimages/curl:latest
    depends_on:
      vampi:
        condition: service_healthy
    networks:
      - restler-net
    command: ["sh", "-c", "curl -s http://vampi:5000/createdb"]

  restler:
    build:
      context: ../..
      dockerfile: services/restler/Dockerfile.restler
    depends_on:
      init-vampi:
        condition: service_completed_successfully
      vampi:
        condition: service_healthy
    volumes:
      - ../../services/vampi/openapi_specs:/specs
      - ./output:/workspace/fuzzing_results
    networks:
      - restler-net
    environment:
      - OPENAPI_SPEC=/specs/openapi3.yml
      - TARGET_URL=http://vampi:5000
      - MODE=all

networks:
  restler-net:
    driver: bridge