version: "3.8"
services:
  vampi:
    image: erev0s/vampi:latest
    container_name: vampi-restler
    ports:
      - "5000:5000"
    environment:
      - vulnerable=1
      - tokentimetolive=300
    networks:
      - restler-net
    command: ["app.py"]

  init-vampi:
    image: curlimages/curl:latest
    depends_on:
      - vampi
    networks:
      - restler-net
    command: ["sh", "-c", "until curl -s http://vampi:5000/createdb; do sleep 2; done"]

  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    depends_on:
      - init-vampi
    volumes:
      # Assuming the OpenAPI spec is in the vampi folder at ../vampi/openapi_specs/openapi3.yml
      - ../vampi/openapi_specs/openapi3.yml:/workspace/openapi3.yml:ro
      # Mount an output folder from services/restler (it will be created if not present)
      - ./output:/workspace/output
    networks:
      - restler-net
    environment:
      - TARGET_IP=vampi
      - TARGET_PORT=5000
      - RUN_FUZZ_LEAN=true
      - FUZZ_LEAN_TIME_BUDGET=0.05
    entrypoint: ["/service/config/entrypoint.sh"]

networks:
  restler-net:
    driver: bridge
