FROM python:3.8-slim
ARG OPENAPI_SPEC=openapi_specs/openapi3.yml

# Install system dependencies
RUN apt-get update && apt-get install -y \
    wget git curl build-essential libssl-dev && \
    wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && apt-get install -y dotnet-sdk-6.0

# Clone RESTler, install dependencies, and build
RUN git clone https://github.com/microsoft/restler-fuzzer /restler && \
    cd /restler && \
    pip install -r restler/requirements.txt && \
    /usr/local/bin/python ./build-restler.py --dest_dir /restler_bin

# Copy OpenAPI spec and entrypoint script
COPY ${OPENAPI_SPEC} /workspace/api.yml
COPY config/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /workspace
ENTRYPOINT ["/entrypoint.sh"]
