version: '3.8'

services:
  restler:
    build:
      context: .
      dockerfile: Dockerfile.restler
    environment:
      RESTLER_TELEMETRY_OPTOUT: "1"
      TARGET_IP: ${TARGET_HOST}
      TARGET_PORT: ${TARGET_PORT}
    volumes:
      - ${BASE_DIR}/services/vampi/openapi_specs/openapi3.yml:/workspace/spec.yml:ro
      - ${BASE_DIR}/workspace/restler/output:/workspace/output
    networks:
      - restler_network

networks:
  restler_network:
    external: true
    name: restler_network_${NETWORK_SUFFIX}