name: API Fuzzing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  DOCKER_NETWORK_NAME: cicd_network
  VAMPI_RESTLER_PORT: 5003
  VAMPI_WUPPIEFUZZ_PORT: 5002
  VAMPI_EVOMASTER_PORT: 5001
  BASE_DIR: ${{ github.workspace }}

jobs:
  initialize_environment:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Directories
        run: |
          mkdir -p ${{ env.BASE_DIR }}/services/vampi
          mkdir -p ${{ env.BASE_DIR }}/workspace
          mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_workspace
          mkdir -p $HOME/.cargo $HOME/.rustup
        shell: bash

      - name: Cleanup Previous Containers
        if: always()
        run: |
          # Force remove the network first
          sudo docker network rm ${{ env.DOCKER_NETWORK_NAME }} 2>/dev/null || true
          
          # Kill all containers (more aggressive than stop)
          sudo docker ps -q | xargs -r sudo docker kill 2>/dev/null || true
          
          # Force remove all containers without stopping
          sudo docker ps -aq | xargs -r sudo docker rm -f 2>/dev/null || true
          
          # Final cleanup of any dangling resources
          sudo docker system prune -f --volumes 2>/dev/null || true
          
          # Sleep to allow system to settle
          sleep 5
        shell: bash

      - name: Create Docker Network
        run: |
          if ! sudo docker network inspect $DOCKER_NETWORK_NAME >/dev/null 2>&1; then
            for i in {1..3}; do
              if sudo docker network create --subnet=172.20.0.0/16 $DOCKER_NETWORK_NAME; then
                echo "Network created successfully"
                break
              fi
              if [ $i -eq 3 ]; then
                echo "Failed to create network after 3 attempts"
                exit 1
              fi
              echo "Attempt $i failed, retrying..."
              sleep 2
            done
          fi
        shell: bash

  setup_target_application:
    runs-on: self-hosted
    needs: initialize_environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build VAmPI Docker Images
        working-directory: ${{ env.BASE_DIR }}/services/vampi
        run: |
          # Cleanup existing containers
          sudo docker compose -f docker-compose.vampi.yml down --remove-orphans || true
          # Build fresh images
          sudo docker compose -f docker-compose.vampi.yml build --force-rm
        shell: bash

  prepare_fuzzers:
    runs-on: self-hosted
    needs: initialize_environment
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Fuzzer Environment
        run: |
          case "${{ matrix.fuzzer }}" in
            "restler")
              mkdir -p ${{ env.BASE_DIR }}/workspace/restler/{config,output}
              ;;
            "wuppiefuzz")
              mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_workspace
              mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_bin
              ;;
            "evomaster")
              mkdir -p ${{ env.BASE_DIR }}/workspace/evomaster/evomaster_results
              ;;
          esac
        shell: bash

      - name: Get WuppieFuzz Latest Commit
        if: matrix.fuzzer == 'wuppiefuzz'
        id: get-commit
        run: |
          LATEST_COMMIT=$(git ls-remote https://github.com/TNO-S3/WuppieFuzz.git HEAD | cut -f1)
          echo "commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache WuppieFuzz Binary
        if: matrix.fuzzer == 'wuppiefuzz'
        id: cache-wuppiefuzz
        uses: actions/cache@v4
        with:
          path: ${{ env.BASE_DIR }}/wuppiefuzz_bin
          key: wuppiefuzz-${{ steps.get-commit.outputs.commit }}
          restore-keys: |
            wuppiefuzz-

      - name: Setup Rust for WuppieFuzz
        if: matrix.fuzzer == 'wuppiefuzz' && steps.cache-wuppiefuzz.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Build Dependencies
        if: matrix.fuzzer == 'wuppiefuzz' && steps.cache-wuppiefuzz.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
        shell: bash

      - name: Build WuppieFuzz
        if: matrix.fuzzer == 'wuppiefuzz' && steps.cache-wuppiefuzz.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/TNO-S3/WuppieFuzz.git ${{ env.BASE_DIR }}/wuppiefuzz_temp
          cd ${{ env.BASE_DIR }}/wuppiefuzz_temp
          cargo build --release
          cp target/release/wuppiefuzz ${{ env.BASE_DIR }}/wuppiefuzz_bin/
          cd ${{ env.BASE_DIR }}
          rm -rf wuppiefuzz_temp
        shell: bash

      - name: Upload WuppieFuzz Binary
        if: matrix.fuzzer == 'wuppiefuzz'
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-binary
          path: ${{ env.BASE_DIR }}/wuppiefuzz_bin/wuppiefuzz
          if-no-files-found: error
          retention-days: 1

  prepare_openapi_specs:
    runs-on: self-hosted
    needs: initialize_environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate OpenAPI Specs
        run: |
          for fuzzer in "restler" "wuppiefuzz" "evomaster"; do
            case $fuzzer in
              "restler")
                PORT=${{ env.VAMPI_RESTLER_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/workspace/restler"
                ;;
              "wuppiefuzz")
                PORT=${{ env.VAMPI_WUPPIEFUZZ_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/wuppiefuzz_workspace"
                ;;
              "evomaster")
                PORT=${{ env.VAMPI_EVOMASTER_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/workspace/evomaster"
                ;;
            esac
            
            mkdir -p "$OUTPUT_DIR"
            cp ${{ env.BASE_DIR }}/services/vampi/openapi_specs/openapi3.yml "$OUTPUT_DIR/openapi3.yml"
            sed -i "s|http://localhost:5000|http://localhost:$PORT|g" "$OUTPUT_DIR/openapi3.yml"
          done
        shell: bash

  run_fuzzing:
    runs-on: self-hosted
    needs: [setup_target_application, prepare_fuzzers, prepare_openapi_specs]
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build VAmPI Image
        run: |
          cd ${{ env.BASE_DIR }}/services/vampi
          sudo docker build -t vampi:latest .
        shell: bash

      - name: Start VAmPI Container
        run: |
          echo "::group::Container Resource Information"
          echo "Starting container setup at $(date)"
          echo "Available system resources:"
          free -h
          df -h
          echo "::endgroup::"

          # Create network if it doesn't exist
          echo "::group::Network Setup"
          echo "Creating/checking network..."
          sudo docker network create ${{ env.DOCKER_NETWORK_NAME }} || true
          echo "Current docker networks:"
          sudo docker network ls
          echo "::endgroup::"
          
          case "${{ matrix.fuzzer }}" in
            "restler")
              PORT=${{ env.VAMPI_RESTLER_PORT }}
              CONTAINER_NAME="vampi-vulnerable-restler"
              ;;
            "wuppiefuzz")
              PORT=${{ env.VAMPI_WUPPIEFUZZ_PORT }}
              CONTAINER_NAME="vampi-vulnerable-wuppiefuzz"
              ;;
            "evomaster")
              PORT=${{ env.VAMPI_EVOMASTER_PORT }}
              CONTAINER_NAME="vampi-vulnerable-evomaster"
              ;;
          esac
          
          echo "::group::Container Cleanup"
          echo "Removing any existing containers..."
          sudo docker rm -f $CONTAINER_NAME || true
          sudo docker rm -f vampi-${{ matrix.fuzzer }} || true
          echo "Current running containers:"
          sudo docker ps
          echo "::endgroup::"
          
          echo "::group::Container Startup"
          START_TIME=$(date +%s)
          echo "Starting VAmPI container for ${{ matrix.fuzzer }} at $(date)"
          
          # Start VAmPI container with debug logging
          sudo docker run -d --name $CONTAINER_NAME \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -p $PORT:5000 \
            -e APP_DEBUG=1 \
            -e FLASK_DEBUG=1 \
            -e FLASK_ENV=development \
            -e vulnerable=1 \
            -e tokentimetolive=300 \
            vampi:latest

          # Verify container is running
          echo "Verifying container status..."
          if ! sudo docker ps | grep -q $CONTAINER_NAME; then
            echo "Container failed to start. Container logs:"
            sudo docker logs $CONTAINER_NAME
            echo "Container status:"
            sudo docker inspect $CONTAINER_NAME
            exit 1
          fi

          # Wait for VAmPI to be ready with more verbose output
          echo "Waiting for container to be ready..."
          for i in {1..30}; do
            echo "Attempt $i: Checking container and port status"
            
            # Check if container is still running
            if ! sudo docker ps | grep -q $CONTAINER_NAME; then
              echo "Container stopped running. Logs:"
              sudo docker logs $CONTAINER_NAME
              exit 1
            fi
            
            # Check port binding
            echo "Port binding status:"
            sudo netstat -tulpn | grep $PORT || true
            
            # Try health check
            echo "Attempting health check..."
            if curl -v --connect-timeout 5 http://localhost:$PORT/health 2>&1; then
              END_TIME=$(date +%s)
              DURATION=$((END_TIME - START_TIME))
              echo "VAmPI is ready after $DURATION seconds"
              echo "Container resource usage:"
              sudo docker stats $CONTAINER_NAME --no-stream
              break
            fi
            
            if [ $i -eq 30 ]; then
              END_TIME=$(date +%s)
              DURATION=$((END_TIME - START_TIME))
              echo "VAmPI failed to start after $DURATION seconds"
              echo "Docker logs:"
              sudo docker logs $CONTAINER_NAME
              echo "Container status:"
              sudo docker inspect $CONTAINER_NAME
              echo "Process list inside container:"
              sudo docker exec $CONTAINER_NAME ps aux || true
              echo "Network interfaces inside container:"
              sudo docker exec $CONTAINER_NAME ip addr || true
              exit 1
            fi
            echo "Waiting for VAmPI to start... ($i/30)"
            sleep 2
          done
          echo "::endgroup::"

          echo "::group::Final Status"
          echo "Container status:"
          sudo docker ps --filter "name=$CONTAINER_NAME" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
          echo "Container resource usage:"
          sudo docker stats $CONTAINER_NAME --no-stream
          echo "Network connectivity:"
          sudo docker network inspect ${{ env.DOCKER_NETWORK_NAME }}
          echo "Container logs:"
          sudo docker logs $CONTAINER_NAME
          echo "::endgroup::"
        shell: bash

  summarize_results:
    runs-on: self-hosted
    needs: run_fuzzing
    steps:
      - name: Download Fuzzer Results
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.fuzzer }}-results
          path: all_results/${{ matrix.fuzzer }}-results
          if-no-files-found: warn

      - name: List Downloaded Artifacts
        run: |
          echo "Listing ${{ matrix.fuzzer }} Results:"
          ls -la all_results/${{ matrix.fuzzer }}-results || echo "${{ matrix.fuzzer }} results directory not found."
        shell: bash
        continue-on-error: true

      - name: Final Cleanup
        if: always()
        run: |
          echo "Pruning Docker containers..."
          sudo docker container prune -f || echo "Failed to prune Docker containers."
          echo "Pruning Docker networks..."
          sudo docker network prune -f || echo "Failed to prune Docker networks."
        shell: bash

  cleanup_all:
    runs-on: self-hosted
    needs: summarize_results
    if: always()
    steps:
      - name: Cleanup Docker Resources
        run: |
          echo "Cleaning up Docker resources..."
          # Clean up containers
          sudo docker compose -f ${{ env.BASE_DIR }}/services/vampi/docker-compose.vampi.yml down --remove-orphans || true
          sudo docker compose -f ${{ env.BASE_DIR }}/workspace/restler/docker-compose.restler.yml down --remove-orphans || true
          sudo docker compose -f ${{ env.BASE_DIR }}/workspace/evomaster/docker-compose.evomaster.yml down --remove-orphans || true
          
          # Remove network if it exists
          if sudo docker network inspect $DOCKER_NETWORK_NAME >/dev/null 2>&1; then
            sudo docker network rm $DOCKER_NETWORK_NAME || true
          fi
        shell: bash

      - name: Cleanup Workspace
        run: |
          echo "Cleaning up workspace..."
          rm -rf ${{ env.BASE_DIR }}/workspace/restler/output/* || true
          rm -rf ${{ env.BASE_DIR }}/wuppiefuzz_workspace/reports/* || true
          rm -rf ${{ env.BASE_DIR }}/workspace/evomaster/evomaster_results/* || true
        shell: bash
