name: API Fuzzing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  DOCKER_NETWORK_NAME: cicd_network
  VAMPI_RESTLER_PORT: 5012
  VAMPI_WUPPIEFUZZ_PORT: 5022
  VAMPI_EVOMASTER_PORT: 5032
  BASE_DIR: ${{ github.workspace }}

jobs:
  initialize_environment:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Directories
        run: |
          mkdir -p ${{ env.BASE_DIR }}/services/vampi
          mkdir -p ${{ env.BASE_DIR }}/workspace
          mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_workspace
          mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_bin
          mkdir -p $HOME/.cargo $HOME/.rustup
        shell: bash

      - name: Cleanup Previous Containers
        if: always()
        run: |
          # Stop and remove any existing containers from previous runs
          docker ps -q | xargs -r docker rm -f || true
          
          # Remove the network if it exists
          docker network rm ${{ env.DOCKER_NETWORK_NAME }} || true
        shell: bash

      - name: Create Docker Network
        run: docker network create ${{ env.DOCKER_NETWORK_NAME }} || true
        shell: bash

  setup_target_application:
    runs-on: self-hosted
    needs: [initialize_environment]
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Directory Structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of services directory:"
          ls -la services || echo "services directory not found"
        shell: bash

      - name: Start VAmPI Container
        run: |
          case "${{ matrix.fuzzer }}" in
            "restler")
              cd services/vampi || exit 1
              echo "Starting VAmPI for RESTler on port 5012"
              
              # Clean up any existing container first
              docker rm -f vampi-vulnerable-5012 || true
              
              # Start the container with debug output
              PORT=5012 docker compose up -d vampi-vulnerable
              
              # Show container status
              echo "Container status:"
              docker ps -a
              echo "Network status:"
              docker network inspect cicd_network
              
              echo "Waiting for VAmPI RESTler instance..."
              for i in {1..30}; do
                if curl -s -f http://localhost:5012/; then
                  echo "VAmPI RESTler instance is ready!"
                  break
                fi
                if [ $i -eq 30 ]; then
                  echo "VAmPI failed to start. Container logs:"
                  docker logs vampi-vulnerable-5012
                  docker ps -a
                  exit 1
                fi
                echo "Waiting for VAmPI to be ready (attempt $i/30)..."
                sleep 2
              done
              ;;
              
            "wuppiefuzz")
              cd services/vampi || exit 1
              echo "Starting VAmPI for WuppieFuzz on port 5022"
              
              # Clean up any existing container first
              docker rm -f vampi-vulnerable-5022 || true
              
              # Start the container with debug output
              PORT=5022 docker compose up -d vampi-vulnerable
              
              # Show container status
              echo "Container status:"
              docker ps -a
              
              echo "Waiting for VAmPI WuppieFuzz instance..."
              for i in {1..30}; do
                if curl -s -f http://localhost:5022/; then
                  echo "VAmPI WuppieFuzz instance is ready!"
                  break
                fi
                if [ $i -eq 30 ]; then
                  echo "VAmPI failed to start. Container logs:"
                  docker logs vampi-vulnerable-5022
                  docker ps -a
                  exit 1
                fi
                echo "Waiting for VAmPI to be ready (attempt $i/30)..."
                sleep 2
              done
              ;;
              
            "evomaster")
              cd services/vampi || exit 1
              echo "Starting VAmPI for EvoMaster on port 5032"
              
              # Clean up any existing container first
              docker rm -f vampi-vulnerable-5032 || true
              
              # Start the container with debug output
              PORT=5032 docker compose up -d vampi-vulnerable
              
              # Show container status
              echo "Container status:"
              docker ps -a
              
              echo "Waiting for VAmPI EvoMaster instance..."
              for i in {1..30}; do
                if curl -s -f http://localhost:5032/; then
                  echo "VAmPI EvoMaster instance is ready!"
                  break
                fi
                if [ $i -eq 30 ]; then
                  echo "VAmPI failed to start. Container logs:"
                  docker logs vampi-vulnerable-5032
                  docker ps -a
                  exit 1
                fi
                echo "Waiting for VAmPI to be ready (attempt $i/30)..."
                sleep 2
              done
              ;;
          esac
        shell: bash

  prepare_fuzzers:
    runs-on: self-hosted
    needs: initialize_environment
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Fuzzer Environment
        run: |
          case "${{ matrix.fuzzer }}" in
            "restler")
              mkdir -p ${{ env.BASE_DIR }}/workspace/restler/{config,output}
              ;;
            "wuppiefuzz")
              mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_workspace
              mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_bin
              ;;
            "evomaster")
              mkdir -p ${{ env.BASE_DIR }}/workspace/evomaster/evomaster_results
              ;;
          esac
        shell: bash

      - name: Get WuppieFuzz Latest Commit
        if: matrix.fuzzer == 'wuppiefuzz'
        id: get-commit
        run: |
          LATEST_COMMIT=$(git ls-remote https://github.com/TNO-S3/WuppieFuzz.git HEAD | cut -f1)
          echo "commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache WuppieFuzz Binary
        if: matrix.fuzzer == 'wuppiefuzz'
        id: cache-wuppiefuzz
        uses: actions/cache@v4
        with:
          path: ${{ env.BASE_DIR }}/wuppiefuzz_bin
          key: wuppiefuzz-${{ steps.get-commit.outputs.commit }}
          restore-keys: |
            wuppiefuzz-

      - name: Setup Rust for WuppieFuzz
        if: matrix.fuzzer == 'wuppiefuzz' && steps.cache-wuppiefuzz.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Build Dependencies
        if: matrix.fuzzer == 'wuppiefuzz' && steps.cache-wuppiefuzz.outputs.cache-hit != 'true'
        run: |
          apt-get update
          apt-get install -y build-essential pkg-config libssl-dev
        shell: bash

      - name: Build WuppieFuzz
        if: matrix.fuzzer == 'wuppiefuzz' && steps.cache-wuppiefuzz.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/TNO-S3/WuppieFuzz.git ${{ env.BASE_DIR }}/wuppiefuzz_temp
          cd ${{ env.BASE_DIR }}/wuppiefuzz_temp
          cargo build --release
          cp target/release/wuppiefuzz ${{ env.BASE_DIR }}/wuppiefuzz_bin/
          cd ${{ env.BASE_DIR }}
          rm -rf wuppiefuzz_temp
        shell: bash

      - name: Upload WuppieFuzz Binary
        if: matrix.fuzzer == 'wuppiefuzz'
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-binary
          path: ${{ env.BASE_DIR }}/wuppiefuzz_bin/wuppiefuzz
          if-no-files-found: error
          retention-days: 1

  prepare_openapi_specs:
    runs-on: self-hosted
    needs: initialize_environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate OpenAPI Specs
        run: |
          for fuzzer in "restler" "wuppiefuzz" "evomaster"; do
            case $fuzzer in
              "restler")
                PORT=${{ env.VAMPI_RESTLER_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/workspace/restler"
                ;;
              "wuppiefuzz")
                PORT=${{ env.VAMPI_WUPPIEFUZZ_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/wuppiefuzz_workspace"
                ;;
              "evomaster")
                PORT=${{ env.VAMPI_EVOMASTER_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/workspace/evomaster"
                ;;
            esac
            
            mkdir -p "$OUTPUT_DIR"
            cp ${{ env.BASE_DIR }}/services/vampi/openapi_specs/openapi3.yml "$OUTPUT_DIR/openapi3.yml"
            sed -i "s|http://localhost:5000|http://localhost:$PORT|g" "$OUTPUT_DIR/openapi3.yml"
          done
        shell: bash

  run_fuzzing:
    runs-on: self-hosted
    needs: [prepare_fuzzers, prepare_openapi_specs, setup_target_application]
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Fuzzer
        run: |
          case "${{ matrix.fuzzer }}" in
            "restler")
              cd services/restler || exit 1
              echo "Running RESTler fuzzer"
              docker compose -f docker-compose.restler.yml up --build
              ;;
              
            "wuppiefuzz")
              cd services/wuppiefuzz || exit 1
              echo "Running WuppieFuzz fuzzer"
              VAMPI_WUPPIEFUZZ_URL=http://vampi-vulnerable:5000 docker compose -f docker-compose.wuppie.yml up --build
              ;;
              
            "evomaster")
              cd services/evomaster || exit 1
              echo "Running EvoMaster fuzzer"
              docker compose -f docker-compose.evomaster.yml up --build
              ;;
          esac
        shell: bash

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.fuzzer }}-results
          path: |
            ${{ env.BASE_DIR }}/workspace/restler/output/**
            ${{ env.BASE_DIR }}/wuppiefuzz_workspace/reports/**
            ${{ env.BASE_DIR }}/workspace/evomaster/evomaster_results/**
          if-no-files-found: warn

      - name: Cleanup
        if: always()
        run: |
          cd ${{ env.BASE_DIR }}/services/vampi
          
          # Clean up all docker compose files and their containers
          for file in docker-compose.*.yaml; do
            if [ -f "$file" ]; then
              echo "Cleaning up $file"
              docker compose -f "$file" down --remove-orphans
            fi
          done
          
          # Additional cleanup of any stray containers
          docker ps -a | grep 'vampi-' | awk '{print $1}' | xargs -r docker rm -f
        shell: bash

  summarize_results:
    runs-on: self-hosted
    needs: run_fuzzing
    steps:
      - name: Download Fuzzer Results
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.fuzzer }}-results
          path: all_results/${{ matrix.fuzzer }}-results
          if-no-files-found: warn

      - name: List Downloaded Artifacts
        run: |
          echo "Listing ${{ matrix.fuzzer }} Results:"
          ls -la all_results/${{ matrix.fuzzer }}-results || echo "${{ matrix.fuzzer }} results directory not found."
        shell: bash
        continue-on-error: true

      - name: Final Cleanup
        if: always()
        run: |
          echo "Pruning Docker containers..."
          docker container prune -f || echo "Failed to prune Docker containers."
          echo "Pruning Docker networks..."
          docker network prune -f || echo "Failed to prune Docker networks."
        shell: bash
