name: API Fuzzing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  DOCKER_NETWORK_NAME: cicd_network
  VAMPI_RESTLER_PORT: 5012
  VAMPI_WUPPIEFUZZ_PORT: 5022
  VAMPI_EVOMASTER_PORT: 5032
  BASE_DIR: ${{ github.workspace }}

jobs:
  initialize_environment:
    runs-on: self-hosted
    outputs:
      runner-label: ${{ runner.name }}
      swarm-manager-ip: ${{ env.SWARM_MANAGER_IP }}
      swarm-worker-token: ${{ env.SWARM_WORKER_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Base Directories
        run: |
          mkdir -p ${{ env.BASE_DIR }}/services/vampi
          mkdir -p ${{ env.BASE_DIR }}/workspace
          mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_workspace
          mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_bin
          mkdir -p $HOME/.cargo $HOME/.rustup
        shell: bash

      - name: Cleanup Previous Containers
        if: always()
        run: |
          echo "Cleaning up previous containers..."
          docker ps -q | xargs -r docker rm -f || true
          echo "Cleanup complete"
        shell: bash

      - name: Setup Docker Swarm
        run: |
          echo "Setting up Docker Swarm..."
          
          # Force leave any existing swarm
          docker swarm leave -f || true
          sleep 2
          
          # Get the IP address
          IP=$(hostname -I | awk '{print $1}')
          echo "Using IP: $IP"
          
          # Initialize swarm
          if ! docker swarm init --advertise-addr $IP; then
            echo "Failed to initialize swarm"
            exit 1
          fi
          
          # Get and store tokens
          MANAGER_TOKEN=$(docker swarm join-token manager -q)
          WORKER_TOKEN=$(docker swarm join-token worker -q)
          echo "SWARM_MANAGER_TOKEN=${MANAGER_TOKEN}" >> $GITHUB_ENV
          echo "SWARM_WORKER_TOKEN=${WORKER_TOKEN}" >> $GITHUB_ENV
          echo "SWARM_MANAGER_IP=${IP}" >> $GITHUB_ENV
          
          # Create network
          echo "Creating overlay network..."
          docker network create --driver overlay --attachable ${{ env.DOCKER_NETWORK_NAME }} || {
            echo "Failed to create network"
            docker network ls
            exit 1
          }
          
          # Verify setup
          echo "=== Swarm Status ==="
          docker info | grep -A5 "Swarm:"
          echo "=== Node List ==="
          docker node ls
          echo "=== Network List ==="
          docker network ls
        shell: bash

      - name: Verify Environment
        run: |
          echo "=== Environment Variables ==="
          env | grep SWARM || echo "No SWARM variables set"
          echo "=== Docker Info ==="
          docker info
          echo "=== Process List ==="
          ps aux | grep docker
        shell: bash

      - name: Verify Network
        run: |
          echo "Network details:"
          docker network inspect ${{ env.DOCKER_NETWORK_NAME }}
        shell: bash

  setup_target_application:
    runs-on: self-hosted
    needs: [initialize_environment]
    env:
      SWARM_MANAGER_IP: ${{ needs.initialize_environment.outputs.swarm-manager-ip }}
      SWARM_WORKER_TOKEN: ${{ needs.initialize_environment.outputs.swarm-worker-token }}
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Directory Structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of services directory:"
          ls -la services || echo "services directory not found"
        shell: bash

      - name: Start VAmPI Container
        run: |
          cd services/vampi
          
          # Cleanup any existing containers
          echo "Cleaning up existing containers..."
          docker compose down -v || true
          
          # Ensure we're in the swarm
          if ! docker info --format '{{.Swarm.LocalNodeState}}' | grep -q "active"; then
            echo "Node not in swarm, joining..."
            docker swarm join --token ${{ env.SWARM_WORKER_TOKEN }} ${{ env.SWARM_MANAGER_IP }}:2377 || {
              echo "Failed to join swarm"
              exit 1
            }
          fi
          
          # Verify network exists
          if ! docker network ls | grep -q ${{ env.DOCKER_NETWORK_NAME }}; then
            echo "Network not found, waiting for it..."
            for i in {1..30}; do
              if docker network ls | grep -q ${{ env.DOCKER_NETWORK_NAME }}; then
                echo "Network is now available"
                break
              fi
              if [ $i -eq 30 ]; then
                echo "Network never became available"
                exit 1
              fi
              echo "Waiting for network... attempt $i/30"
              sleep 1
            done
          fi
          
          # Start containers
          echo "Starting VAmPI for ${{ matrix.fuzzer }} on port ${{ env.VAMPI_PORT }}"
          export PORT=${{ env.VAMPI_PORT }}
          export DOCKER_NETWORK_NAME=${{ env.DOCKER_NETWORK_NAME }}
          
          # Try to start containers with retry
          MAX_RETRIES=3
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            if docker compose up -d; then
              # Wait for containers to be healthy
              for i in {1..30}; do
                if curl -s http://localhost:${{ env.VAMPI_PORT }}/api/v1/docs > /dev/null; then
                  echo "VAmPI is up and running"
                  docker compose ps
                  exit 0
                fi
                echo "Waiting for VAmPI to be ready... attempt $i/30"
                sleep 1
              done
            fi
            
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo "Failed to start/verify containers, attempt $RETRY_COUNT of $MAX_RETRIES"
            docker compose down -v
            sleep 5
          done
          
          echo "Failed to start containers after $MAX_RETRIES attempts"
          docker compose logs
          exit 1
        env:
          VAMPI_PORT: ${{ matrix.fuzzer == 'restler' && env.VAMPI_RESTLER_PORT || matrix.fuzzer == 'wuppiefuzz' && env.VAMPI_WUPPIEFUZZ_PORT || env.VAMPI_EVOMASTER_PORT }}
        shell: bash

  prepare_fuzzers:
    runs-on: self-hosted
    needs: [initialize_environment]
    env:
      SWARM_MANAGER_IP: ${{ needs.initialize_environment.outputs.swarm-manager-ip }}
      SWARM_WORKER_TOKEN: ${{ needs.initialize_environment.outputs.swarm-worker-token }}
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup RESTler
        if: matrix.fuzzer == 'restler'
        run: |
          echo "Setting up RESTler..."
          # RESTler setup steps here
        shell: bash

      - name: Setup WuppieFuzz
        if: matrix.fuzzer == 'wuppiefuzz'
        run: |
          echo "Setting up WuppieFuzz..."
          # WuppieFuzz setup steps here
        shell: bash

      - name: Setup EvoMaster
        if: matrix.fuzzer == 'evomaster'
        run: |
          echo "Setting up EvoMaster..."
          
          # Create evomaster directory
          mkdir -p tools/evomaster
          cd tools/evomaster
          
          # Download EvoMaster JAR
          echo "Downloading EvoMaster..."
          curl -L -o evomaster.jar https://github.com/WebFuzzing/EvoMaster/releases/download/v3.3.0/evomaster.jar
          
          # Verify download
          if [ ! -f evomaster.jar ]; then
            echo "Failed to download EvoMaster"
            exit 1
          fi
          
          # Test EvoMaster installation
          echo "Testing EvoMaster installation..."
          java -jar evomaster.jar --version
          
          # Create evomaster configuration
          echo "Creating EvoMaster configuration..."
          cat > evomaster.yml << EOL
          blackBox: true
          testTargetUrl: http://localhost:${{ env.VAMPI_EVOMASTER_PORT }}
          openApiUrl: ./openapi_specs/openapi3.yml
          outputFormat: JAVA_JUNIT_5
          maxTime: 1h
          EOL
          
          echo "EvoMaster setup complete"
        shell: bash

      - name: Upload Fuzzer Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fuzzer-${{ matrix.fuzzer }}-artifacts
          path: |
            tools/**/*
          retention-days: 1

  prepare_openapi_specs:
    runs-on: self-hosted
    needs: [setup_target_application]
    if: always() && !contains(needs.*.result, 'failure')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate OpenAPI Specs
        run: |
          for fuzzer in "restler" "wuppiefuzz" "evomaster"; do
            case $fuzzer in
              "restler")
                PORT=${{ env.VAMPI_RESTLER_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/workspace/restler"
                ;;
              "wuppiefuzz")
                PORT=${{ env.VAMPI_WUPPIEFUZZ_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/wuppiefuzz_workspace"
                ;;
              "evomaster")
                PORT=${{ env.VAMPI_EVOMASTER_PORT }}
                OUTPUT_DIR="${{ env.BASE_DIR }}/workspace/evomaster"
                ;;
            esac
            
            mkdir -p "$OUTPUT_DIR"
            cp ${{ env.BASE_DIR }}/services/vampi/openapi_specs/openapi3.yml "$OUTPUT_DIR/openapi3.yml"
            sed -i "s|http://localhost:5000|http://localhost:$PORT|g" "$OUTPUT_DIR/openapi3.yml"
          done
        shell: bash

  run_fuzzing:
    runs-on: self-hosted
    needs: [prepare_fuzzers, prepare_openapi_specs, setup_target_application]
    strategy:
      matrix:
        fuzzer: [restler, wuppiefuzz, evomaster]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Fuzzer Artifacts
        uses: actions/download-artifact@v3
        with:
          name: fuzzer-${{ matrix.fuzzer }}-artifacts
          path: tools

      - name: Download OpenAPI Specs
        uses: actions/download-artifact@v3
        with:
          name: openapi-specs
          path: openapi_specs

      - name: Run RESTler
        if: matrix.fuzzer == 'restler'
        run: |
          echo "Running RESTler..."
          # RESTler execution steps here
        shell: bash

      - name: Run WuppieFuzz
        if: matrix.fuzzer == 'wuppiefuzz'
        run: |
          echo "Running WuppieFuzz..."
          # WuppieFuzz execution steps here
        shell: bash

      - name: Run EvoMaster
        if: matrix.fuzzer == 'evomaster'
        run: |
          echo "Running EvoMaster..."
          cd tools/evomaster
          
          # Ensure EvoMaster jar is executable
          chmod +x evomaster.jar
          
          # Create results directory
          mkdir -p results
          
          echo "Starting EvoMaster with configuration:"
          cat evomaster.yml
          
          # Run EvoMaster
          java -jar evomaster.jar \
            --blackBox true \
            --testTargetUrl http://localhost:${{ env.VAMPI_EVOMASTER_PORT }} \
            --openApiUrl ../../openapi_specs/openapi3.yml \
            --outputFormat JAVA_JUNIT_5 \
            --maxTime 1h \
            --outputFolder ./results \
            --problemType REST
          
          echo "EvoMaster execution completed"
          
          # Check results
          if [ -d "results" ]; then
            echo "Test results generated successfully"
            ls -la results/
          else
            echo "No results directory found"
            exit 1
          fi
        shell: bash

      - name: Upload Fuzzing Results
        uses: actions/upload-artifact@v3
        with:
          name: fuzzing-results-${{ matrix.fuzzer }}
          path: |
            tools/**/results
            tools/**/output
          retention-days: 1

  summarize_results:
    runs-on: self-hosted
    needs: run_fuzzing
    steps:
      - name: Download Fuzzer Results
        uses: actions/download-artifact@v4
        with:
          name: fuzzing-results-${{ matrix.fuzzer }}
          path: all_results/${{ matrix.fuzzer }}-results
          if-no-files-found: warn

      - name: List Downloaded Artifacts
        run: |
          echo "Listing ${{ matrix.fuzzer }} Results:"
          ls -la all_results/${{ matrix.fuzzer }}-results || echo "${{ matrix.fuzzer }} results directory not found."
        shell: bash
        continue-on-error: true

      - name: Final Cleanup
        if: always()
        run: |
          echo "Pruning Docker containers..."
          docker container prune -f || echo "Failed to prune Docker containers."
          echo "Pruning Docker networks..."
          docker network prune -f || echo "Failed to prune Docker networks."
        shell: bash
