name: Fuzz DVAPI with Multiple Tools

on:
  push:
    branches: [More-endpoints]
  pull_request:
    branches: [More-endpoints]

permissions:
  contents: read
  packages: read

jobs:
  evomaster:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environment Variables
        run: |
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^#.*$ ]] && [[ ! -z "$line" ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < targets/dvapi/config.env

      - name: Clone DVAPI Repository
        run: |
          cd targets/dvapi
          git clone https://github.com/payatu/DVAPI.git

      - name: Start DVAPI Container
        run: |
          cd targets/dvapi
          docker compose up -d --build
          echo "Waiting for DVAPI to be ready..."
          timeout 30 bash -c 'until curl -s http://localhost:3000/health; do sleep 1; done'
          sleep 5

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Download EvoMaster
        run: |
          curl -L -o evomaster.jar https://github.com/EMResearch/EvoMaster/releases/download/v3.4.0/evomaster.jar

      - name: Run EvoMaster in Blackbox Mode
        run: |
          java -jar evomaster.jar \
            --blackBox true \
            --bbTargetUrl http://localhost:3000 \
            --outputFormat PYTHON_UNITTEST \
            --maxTime 1h \
            --outputFolder generated_tests/dvapi \
            --testSuiteFileName dvapi_test \
            --maxTestSize 100

      - name: Upload EvoMaster Results
        uses: actions/upload-artifact@v4
        with:
          name: dvapi-evomaster-results
          path: generated_tests/dvapi

  wuppiefuzz:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environment Variables
        run: |
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^#.*$ ]] && [[ ! -z "$line" ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < targets/dvapi/config.env

      - name: Clone DVAPI Repository
        run: |
          cd targets/dvapi
          git clone https://github.com/payatu/DVAPI.git

      - name: Start DVAPI Container
        run: |
          cd targets/dvapi
          docker compose up -d --build
          echo "Waiting for DVAPI to be ready..."
          timeout 30 bash -c 'until curl -s http://localhost:3000/health; do sleep 1; done'
          sleep 5

      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Clone WuppieFuzz Repository
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release

      - name: Generate Initial Corpus
        run: |
          cd WuppieFuzz
          ./target/release/wuppiefuzz output-corpus \
            --openapi-spec http://localhost:3000/swagger \
            corpus_directory

      - name: Run WuppieFuzz Fuzzing Campaign
        run: |
          cd WuppieFuzz
          ./target/release/wuppiefuzz fuzz \
            --report \
            --log-level info \
            --initial-corpus corpus_directory \
            --timeout 3600 \
            http://localhost:3000/swagger

      - name: Upload Fuzzing Report
        uses: actions/upload-artifact@v4
        with:
          name: dvapi-fuzzing-report
          path: WuppieFuzz/reports/

  restler:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      BASE_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environment Variables
        run: |
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^#.*$ ]] && [[ ! -z "$line" ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < targets/dvapi/config.env

      - name: Clone DVAPI Repository
        run: |
          cd targets/dvapi
          git clone https://github.com/payatu/DVAPI.git

      - name: Start DVAPI Container
        run: |
          cd targets/dvapi
          docker compose up -d --build
          echo "Waiting for DVAPI to be ready..."
          timeout 30 bash -c 'until curl -s http://localhost:3000/health; do sleep 1; done'
          sleep 5

      - name: Prepare Environment
        run: |
          mkdir -p "$BASE_DIR/fuzzers/restler/output"
          sudo chmod -R 777 "$BASE_DIR/fuzzers/restler/output"

      - name: Run RESTler and DVAPI
        run: |
          cd fuzzers/restler
          docker compose -f docker-compose.restler.yml up --abort-on-container-exit

      - name: Upload RESTler Results
        uses: actions/upload-artifact@v4
        with:
          name: dvapi-restler-results
          path: |
            ${{ github.workspace }}/fuzzers/restler/output/Test/
            ${{ github.workspace }}/fuzzers/restler/output/FuzzLean/
            ${{ github.workspace }}/fuzzers/restler/output/Fuzz/

  schemathesis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environment Variables
        run: |
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^#.*$ ]] && [[ ! -z "$line" ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < targets/dvapi/config.env

      - name: Clone DVAPI Repository
        run: |
          cd targets/dvapi
          git clone https://github.com/payatu/DVAPI.git

      - name: Start DVAPI Container
        run: |
          cd targets/dvapi
          docker compose up -d --build
          echo "Waiting for DVAPI to be ready..."
          timeout 30 bash -c 'until curl -s http://localhost:3000/health; do sleep 1; done'
          sleep 5

      - name: Run Schemathesis
        run: |
          cd fuzzers/schemathesis
          docker compose -f docker-compose.schemathesis.yml up --abort-on-container-exit

      - name: Upload Schemathesis Results
        uses: actions/upload-artifact@v4
        with:
          name: dvapi-schemathesis-results
          path: fuzzers/schemathesis/output