name: WuppieFuzz CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_fuzz:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and run services with Docker Compose
      - name: Build and run services with Docker Compose
        env:
          SMTP_USER: 'dummy_user'
          SMTP_PASS: 'dummy_pass'
          SMTP_HOST: 'smtp.example.com'
          SMTP_PORT: '587'
        run: |
          docker-compose up -d --build

      # Step 4: Wait for services to start
      - name: Wait for services to start
        run: sleep 15

      # Step 5: Install Rust toolchain
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 6: Clone WuppieFuzz repository
      - name: Clone WuppieFuzz repository
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

      # Step 7: Build WuppieFuzz
      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release
          cd ..

      # Step 8: Add WuppieFuzz to PATH
      - name: Add WuppieFuzz to PATH
        run: echo "${{ github.workspace }}/WuppieFuzz/target/release" >> $GITHUB_PATH

      # Step 9: Prepare OpenAPI specification
      - name: Prepare OpenAPI specification
        run: |
          cp server/swagger.yaml openapi.yaml

      # Step 10: Generate initial corpus
      - name: Generate initial corpus
        run: wuppiefuzz output-corpus --openapi-spec openapi.yaml corpus_directory

      # Step 11: Run WuppieFuzz fuzzing
      - name: Run WuppieFuzz
        run: |
          wuppiefuzz fuzz --report --log-level info --initial-corpus corpus_directory --timeout 300 --openapi-spec openapi.yaml --base-url http://localhost:3001

      # Step 12: Upload WuppieFuzz report
      - name: Upload WuppieFuzz report
        uses: actions/upload-artifact@v3
        with:
          name: wuppiefuzz-report
          path: reports/

      # Step 13: Stop and remove Docker containers
      - name: Stop and remove Docker containers
        if: always()
        run: docker-compose down
