name: WuppieFuzz CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_fuzz:
    runs-on: ubuntu-latest  # Use 'ubuntu-latest' if you don't have a self-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build and run services with Docker Compose
      - name: Build and run services with Docker Compose
        env:
          SMTP_USER: 'dummy_user'
          SMTP_PASS: 'dummy_pass'
          SMTP_HOST: 'smtp.example.com'
          SMTP_PORT: '587'
        run: |
          docker-compose up -d --build

      # Step 4: Wait for services to start
      - name: Wait for services to start
        run: sleep 15

      # Step 5: Install Rust toolchain
        # Update to the latest version if available
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Step 6: Install dependencies for WuppieFuzz
      - name: Install dependencies for WuppieFuzz
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      # Step 7: Clone WuppieFuzz repository
      - name: Clone WuppieFuzz repository
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

      # Step 8: Build WuppieFuzz
      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release
          cd ..

      # Step 9: Add WuppieFuzz to PATH
      - name: Add WuppieFuzz to PATH
        run: echo "${{ github.workspace }}/WuppieFuzz/target/release" >> $GITHUB_PATH

     
      # Step 10: Prepare OpenAPI specification
      # - name: Prepare OpenAPI specification
      #   run: |
      #     cp openapi.yaml openapi.yaml

      
      # Step 11: Generate initial corpus
      - name: Generate initial corpus
        run: wuppiefuzz output-corpus --openapi-spec openapi.yaml corpus_directory

      
      # Step 12: Run WuppieFuzz fuzzing
      - name: Run WuppieFuzz
        env:
          RUST_BACKTRACE: 1
        run: |
          wuppiefuzz fuzz --report --log-level info --initial-corpus corpus_directory \
          --timeout 300 openapi.yaml

      # Step 13: Upload WuppieFuzz report
      - name: Upload WuppieFuzz report
        uses: actions/upload-artifact@v3
        with:
          name: wuppiefuzz-report
          path: reports/

      # Step 14: Stop and remove Docker containers
      - name: Stop and remove Docker containers
        if: always()
        run: docker-compose down
