name: WuppieFuzz CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_fuzz:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Clone the Vulnerable REST API repository
      - name: Clone Vulnerable REST API repository
        run: git clone https://github.com/bnematzadeh/vulnerable-rest-api.git

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Run Docker Compose to start the services
      - name: Run Docker Compose
        run: |
          cd vulnerable-rest-api
          docker-compose up -d --build

      # Step 5: Wait for the API to start
      - name: Wait for API to start
        run: sleep 10

      # Step 6: Install Python and dependencies
      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      # Step 7: Install WuppieFuzz
      - name: Install WuppieFuzz
        run: pip3 install git+https://github.com/TNO-S3/WuppieFuzz.git

      # Step 8: Prepare OpenAPI specification
      - name: Prepare OpenAPI specification
        run: |
          cp ./vulnerable-rest-api/swagger.yaml ./openapi.yaml

      # Step 9: Generate initial corpus
      - name: Generate initial corpus
        run: wuppiefuzz output-corpus --openapi-spec openapi.yaml corpus_directory

      # Step 10: Run WuppieFuzz fuzzing
      - name: Run WuppieFuzz
        run: |
          wuppiefuzz fuzz --report --log-level info --initial-corpus corpus_directory --timeout 60 --openapi-spec openapi.yaml

      # Step 11: Upload WuppieFuzz report
      - name: Upload WuppieFuzz report
        uses: actions/upload-artifact@v3
        with:
          name: wuppiefuzz-report
          path: reports/

      # Step 12: Copy report.db to Grafana reports directory
      - name: Copy report.db to Grafana reports directory
        run: |
          mkdir -p ./reports/grafana
          cp reports/report.db ./reports/grafana/

      # Step 13: Restart Grafana container to load new data
      - name: Restart Grafana Container
        run: |
          docker-compose up -d --force-recreate grafana-dashboard

      # Step 14: Stop and remove Vulnerable REST API Docker container
      - name: Stop and remove Vulnerable REST API Docker container
        if: always()
        run: |
          docker-compose down
