name: Single Worker API Fuzzing

on:
  push:
    branches: [SingleWorker]
  pull_request:
    branches: [SingleWorker]
  workflow_dispatch:
    inputs:
      restler_time_budget:
        description: RESTler fuzzing time budget (hours)
        required: false
        default: '1'
        type: string
      wuppiefuzz_time_budget:
        description: WuppieFuzz time budget (minutes)
        required: false
        default: '60'
        type: string
      evomaster_time_budget:
        description: EvoMaster time budget (minutes)
        required: false
        default: '10'
        type: string

concurrency:
  group: single-worker-api-fuzzing
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  security-events: write

env:
  BASE_DIR: ${{ github.workspace }}
  DOCKER_BUILDKIT: 1

jobs:
  scan-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build VAmPI Image
        run: docker build -t vampi-vulnerable:latest -f services/vampi/Dockerfile services/vampi

      - name: Scan VAmPI Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: vampi-vulnerable:latest
          format: sarif
          output: trivy-results.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  restler-fuzzing:
    needs: scan-docker-images
    runs-on: self-hosted
    env:
      VAMPI_PORT: 5012
    steps:
      - uses: actions/checkout@v4
      - name: Setup VAmPI Container
        uses: ./.github/actions/setup-vampi
        with:
          port: ${{ env.VAMPI_PORT }}
          network_name: restler_network
          container_name: vampi-restler

      - name: Run RESTler
        uses: ./.github/actions/run-restler
        with:
          base_dir: ${{ env.BASE_DIR }}
          time_budget: ${{ github.event.inputs.restler_time_budget || 1 }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: restler-results
          path: ${{ env.BASE_DIR }}/workspace/restler/output

      - name: Cleanup
        if: always()
        run: |
          docker rm -f vampi-restler || true
          docker network rm restler_network || true
          docker image prune -f || true

  wuppiefuzz-fuzzing:
    needs: scan-docker-images
    runs-on: self-hosted
    env:
      VAMPI_PORT: 5022
    steps:
      - uses: actions/checkout@v4
      - name: Setup VAmPI Container
        uses: ./.github/actions/setup-vampi
        with:
          port: ${{ env.VAMPI_PORT }}
          network_name: wuppiefuzz_network
          container_name: vampi-wuppiefuzz

      - name: Run WuppieFuzz
        uses: ./.github/actions/run-wuppiefuzz
        with:
          port: ${{ env.VAMPI_PORT }}
          time_budget: ${{ github.event.inputs.wuppiefuzz_time_budget || 60 }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wuppiefuzz-results
          path: wuppiefuzz/reports
          if-no-files-found: warn

      - name: Cleanup
        if: always()
        run: |
          docker rm -f vampi-wuppiefuzz || true
          docker network rm wuppiefuzz_network || true
          docker image prune -f || true

  evomaster-fuzzing:
    needs: scan-docker-images
    runs-on: self-hosted
    env:
      VAMPI_PORT: 5032
    steps:
      - uses: actions/checkout@v4
      - name: Setup VAmPI Container
        uses: ./.github/actions/setup-vampi
        with:
          port: ${{ env.VAMPI_PORT }}
          network_name: evomaster_network
          container_name: vampi-evomaster

      - name: Run EvoMaster
        uses: ./.github/actions/run-evomaster
        with:
          time_budget: ${{ github.event.inputs.evomaster_time_budget || 10 }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: evomaster-results
          path: workspace/evomaster/output

      - name: Cleanup
        if: always()
        run: |
          docker rm -f vampi-evomaster || true
          docker network rm evomaster_network || true
          docker image prune -f || true

  process-results:
    needs: [restler-fuzzing, wuppiefuzz-fuzzing, evomaster-fuzzing]
    runs-on: self-hosted
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Process Results
        id: process-results
        uses: ./.github/actions/process-results

      - uses: actions/upload-artifact@v4
        with:
          name: fuzzing-summary
          path: summary/summary.md

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('summary/summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

      - name: Check for Critical Findings
        if: steps.process-results.outputs.critical_findings == '1'
        run: |
          echo "Critical security findings detected! Check the summary for details."
          exit 1
