name: Single Worker API Fuzzing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  DOCKER_NETWORK_NAME: fuzzing_network
  VAMPI_RESTLER_PORT: 5012
  VAMPI_WUPPIEFUZZ_PORT: 5022
  VAMPI_EVOMASTER_PORT: 5032
  BASE_DIR: ${{ github.workspace }}
  FUZZERS: restler wuppiefuzz evomaster
  HEALTH_CHECK_TIMEOUT: 30

jobs:
  fuzzing:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cleanup Previous Runs
        run: |
          # Stop and remove any existing containers
          docker ps -aq | xargs -r docker rm -f
          # Remove existing network if it exists
          docker network rm ${{ env.DOCKER_NETWORK_NAME }} || true
          # Cleanup any leftover volumes
          docker volume prune -f

      - name: Create Docker Network
        run: |
          docker network create ${{ env.DOCKER_NETWORK_NAME }}

      - name: Build VAmPI Images
        run: |
          # Build separate VAmPI instances for each fuzzer
          for FUZZER in ${{ env.FUZZERS }}; do
            docker build \
              --file services/vampi/Dockerfile \
              --build-arg vulnerable=1 \
              --tag vampi-vulnerable-${FUZZER}:latest \
              services/vampi/
          done

      - name: Build Fuzzer Images
        run: |
          # Build WuppieFuzz
          git clone https://github.com/TNO-S3/WuppieFuzz.git temp_wuppiefuzz
          cp -r temp_wuppiefuzz/* services/wuppiefuzz/
          docker build \
            --file services/wuppiefuzz/Dockerfile.wuppiefuzz \
            --tag wuppiefuzz:latest \
            services/wuppiefuzz/
          rm -rf temp_wuppiefuzz

          # Build RESTler
          docker build \
            --file services/restler/Dockerfile.restler \
            --tag restler:latest \
            services/restler/

          # Build EvoMaster
          docker build \
            --file services/evomaster/Dockerfile.evomaster \
            --tag evomaster:latest \
            services/evomaster/

      - name: Start VAmPI Containers
        run: |
          # Start VAmPI for RESTler
          docker run -d \
            --name vampi-restler \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -p ${{ env.VAMPI_RESTLER_PORT }}:5000 \
            -e vulnerable=1 \
            vampi-vulnerable-restler:latest

          # Start VAmPI for WuppieFuzz
          docker run -d \
            --name vampi-wuppiefuzz \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -p ${{ env.VAMPI_WUPPIEFUZZ_PORT }}:5000 \
            -e vulnerable=1 \
            vampi-vulnerable-wuppiefuzz:latest

          # Start VAmPI for EvoMaster
          docker run -d \
            --name vampi-evomaster \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -p ${{ env.VAMPI_EVOMASTER_PORT }}:5000 \
            -e vulnerable=1 \
            vampi-vulnerable-evomaster:latest

          # Wait for all VAmPI instances to be healthy
          for PORT in ${{ env.VAMPI_RESTLER_PORT }} ${{ env.VAMPI_WUPPIEFUZZ_PORT }} ${{ env.VAMPI_EVOMASTER_PORT }}; do
            timeout ${{ env.HEALTH_CHECK_TIMEOUT }} bash -c "until curl -s http://localhost:${PORT}/health > /dev/null; do sleep 1; done"
          done

      - name: Run Fuzzing Tests
        run: |
          # Create volumes for results
          docker volume create restler_output
          docker volume create wuppiefuzz_output
          docker volume create evomaster_output

          # Run RESTler
          docker run --rm \
            --name restler \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -v restler_output:/results \
            -v ${{ github.workspace }}/services/vampi/openapi_specs:/specs \
            restler:latest \
            http://vampi-restler:5000 /specs/openapi3.yml

          # Run WuppieFuzz
          docker run --rm \
            --name wuppiefuzz \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -v wuppiefuzz_output:/results \
            -v ${{ github.workspace }}/services/vampi/openapi_specs:/specs \
            wuppiefuzz:latest \
            http://vampi-wuppiefuzz:5000 /specs/openapi3.yml

          # Run EvoMaster
          docker run --rm \
            --name evomaster \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -v evomaster_output:/results \
            -v ${{ github.workspace }}/services/vampi/openapi_specs:/specs \
            evomaster:latest \
            http://vampi-evomaster:5000 /specs/openapi3.yml

      - name: Collect Results
        run: |
          mkdir -p fuzzing_results
          
          # Copy results from each fuzzer's volume
          for FUZZER in ${{ env.FUZZERS }}; do
            mkdir -p fuzzing_results/${FUZZER}
            docker run --rm \
              -v ${FUZZER}_output:/results \
              -v ${{ github.workspace }}/fuzzing_results/${FUZZER}:/output \
              alpine cp -r /results/* /output/
          done

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-results
          path: fuzzing_results
          retention-days: 7

      - name: Cleanup
        if: always()
        run: |
          # Stop and remove containers
          docker ps -aq | xargs -r docker rm -f
          # Remove network
          docker network rm ${{ env.DOCKER_NETWORK_NAME }} || true
          # Remove volumes
          docker volume rm restler_output wuppiefuzz_output evomaster_output || true
