name: Single Worker API Fuzzing

on:
  push:
    branches: [ SingleWorker ]
  pull_request:
    branches: [ SingleWorker ]

concurrency:
  group: single-worker-api-fuzzing
  cancel-in-progress: true

permissions:
  contents: read

env:
  DOCKER_NETWORK_NAME: fuzzing_network
  VAMPI_RESTLER_PORT: 5012
  VAMPI_WUPPIEFUZZ_PORT: 5022
  VAMPI_EVOMASTER_PORT: 5032
  BASE_DIR: ${{ github.workspace }}
  FUZZERS: restler wuppiefuzz evomaster

jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check Docker Configuration
        run: |
          chmod +x scripts/check-docker.sh
          ./scripts/check-docker.sh
        shell: bash

      - name: Cleanup Previous Run
        run: |
          echo "Cleaning up resources from previous runs..."
          # Remove containers
          docker rm -f vampi-restler vampi-wuppiefuzz vampi-evomaster 2>/dev/null || true
          # Remove network
          docker network rm ${{ env.DOCKER_NETWORK_NAME }} 2>/dev/null || true
          # Clean up dangling images
          docker image prune -f 2>/dev/null || true
          echo "Cleanup completed"
        shell: bash

      - name: Create Docker Network
        run: |
          echo "Creating Docker network: ${{ env.DOCKER_NETWORK_NAME }}..."
          if ! docker network create ${{ env.DOCKER_NETWORK_NAME }}; then
            echo "Failed to create network ${{ env.DOCKER_NETWORK_NAME }}"
            exit 1
          fi
          echo "Network created successfully."
        shell: bash

      - name: Build VAmPI Images
        run: |
          echo "Building VAmPI images..."
          
          # Build VAmPI for RESTler
          docker build -t vampi-vulnerable-restler:latest \
            --build-arg PORT=${{ env.VAMPI_RESTLER_PORT }} \
            -f services/vampi/Dockerfile services/vampi/
          
          # Build VAmPI for WuppieFuzz
          docker build -t vampi-vulnerable-wuppiefuzz:latest \
            --build-arg PORT=${{ env.VAMPI_WUPPIEFUZZ_PORT }} \
            -f services/vampi/Dockerfile services/vampi/
          
          # Build VAmPI for EvoMaster
          docker build -t vampi-vulnerable-evomaster:latest \
            --build-arg PORT=${{ env.VAMPI_EVOMASTER_PORT }} \
            -f services/vampi/Dockerfile services/vampi/
        shell: bash

      - name: Start VAmPI Containers
        run: |
          echo "Starting VAmPI containers..."
          
          # Start VAmPI for RESTler
          docker run -d \
            --name vampi-restler \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -p ${{ env.VAMPI_RESTLER_PORT }}:5000 \
            -e vulnerable=1 \
            --health-cmd "curl -f http://localhost:5000/health || exit 1" \
            --health-interval 10s \
            --health-retries 3 \
            vampi-vulnerable-restler:latest

          # Start VAmPI for WuppieFuzz
          docker run -d \
            --name vampi-wuppiefuzz \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -p ${{ env.VAMPI_WUPPIEFUZZ_PORT }}:5000 \
            -e vulnerable=1 \
            --health-cmd "curl -f http://localhost:5000/health || exit 1" \
            --health-interval 10s \
            --health-retries 3 \
            vampi-vulnerable-wuppiefuzz:latest

          # Start VAmPI for EvoMaster
          docker run -d \
            --name vampi-evomaster \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -p ${{ env.VAMPI_EVOMASTER_PORT }}:5000 \
            -e vulnerable=1 \
            --health-cmd "curl -f http://localhost:5000/health || exit 1" \
            --health-interval 10s \
            --health-retries 3 \
            vampi-vulnerable-evomaster:latest

          echo "Waiting for services to start..."
          # Increased wait time to ensure services are fully ready
          sleep 30

          # Check container health
          FAILED_CONTAINERS=""
          for CONTAINER in vampi-restler vampi-wuppiefuzz vampi-evomaster; do
            echo "Checking health of $CONTAINER..."
            HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' $CONTAINER)
            echo "Health status: $HEALTH_STATUS"
            
            if [ "$HEALTH_STATUS" != "healthy" ]; then
              echo "::error::Container $CONTAINER is not healthy (status: $HEALTH_STATUS)"
              echo "Last health check results:"
              docker inspect --format='{{range .State.Health.Log}}{{.Output}}{{end}}' $CONTAINER
              echo "Container logs:"
              docker logs $CONTAINER
              FAILED_CONTAINERS="$FAILED_CONTAINERS $CONTAINER"
            fi
          done

          if [ ! -z "$FAILED_CONTAINERS" ]; then
            echo "::error::The following containers failed health checks:$FAILED_CONTAINERS"
            exit 1
          fi
          
          echo "All containers are healthy"
        shell: bash

      - name: Build Fuzzer Images
        run: |
          echo "Building fuzzer images..."
          
          # Build RESTler
          docker build -t restler-fuzzer:latest \
            -f services/restler/Dockerfile.restler services/restler/
          
          # Build WuppieFuzz
          if [ -f services/wuppiefuzz/Cargo.toml ]; then
            docker build -t wuppiefuzz:latest \
              -f services/wuppiefuzz/Dockerfile.wuppiefuzz services/wuppiefuzz/
          else
            echo "Warning: WuppieFuzz Cargo.toml not found, skipping build"
          fi
          
          # Build EvoMaster
          docker build -t evomaster:latest \
            -f services/evomaster/Dockerfile.evomaster services/evomaster/
        shell: bash

      - name: Run Fuzzing Tests
        run: |
          echo "Starting fuzzing tests..."
          
          # Create results directory
          mkdir -p ${{ env.BASE_DIR }}/results
          
          # Run RESTler
          echo "Running RESTler..."
          docker run --rm \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -v ${{ env.BASE_DIR }}/results:/results \
            restler-fuzzer:latest \
            --target_ip vampi-restler \
            --target_port 5000 \
            --time_budget 1h || echo "RESTler fuzzing failed"
          
          # Run WuppieFuzz if available
          if docker image inspect wuppiefuzz:latest >/dev/null 2>&1; then
            echo "Running WuppieFuzz..."
            docker run --rm \
              --network ${{ env.DOCKER_NETWORK_NAME }} \
              -v ${{ env.BASE_DIR }}/results:/results \
              wuppiefuzz:latest \
              --target http://vampi-wuppiefuzz:5000 \
              --duration 1h || echo "WuppieFuzz fuzzing failed"
          fi
          
          # Run EvoMaster
          echo "Running EvoMaster..."
          docker run --rm \
            --network ${{ env.DOCKER_NETWORK_NAME }} \
            -v ${{ env.BASE_DIR }}/results:/results \
            evomaster:latest \
            --targetHost vampi-evomaster \
            --targetPort 5000 \
            --maxTime 1h || echo "EvoMaster fuzzing failed"
        shell: bash

      - name: Upload Fuzzing Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fuzzing-results
          path: ${{ env.BASE_DIR }}/results
          retention-days: 14

      - name: Cleanup Resources
        if: always()
        run: |
          echo "Cleaning up resources..."
          # Remove containers
          docker rm -f vampi-restler vampi-wuppiefuzz vampi-evomaster 2>/dev/null || true
          # Remove network
          docker network rm ${{ env.DOCKER_NETWORK_NAME }} 2>/dev/null || true
          # Clean up dangling images
          docker image prune -f 2>/dev/null || true
          echo "Cleanup completed"
        shell: bash

      - name: Process Results
        if: always()
        run: |
          echo "Processing fuzzing results..."
          
          # Check for any discovered vulnerabilities
          if find ${{ env.BASE_DIR }}/results -type f -exec grep -l "vulnerability" {} \; | grep -q .; then
            echo "::warning ::Potential vulnerabilities found in fuzzing results"
          fi
          
          # Generate summary report
          echo "### Fuzzing Test Summary" > ${{ env.BASE_DIR }}/results/summary.md
          echo "Results for each fuzzer:" >> ${{ env.BASE_DIR }}/results/summary.md
          
          for FUZZER in ${{ env.FUZZERS }}; do
            echo "#### $FUZZER" >> ${{ env.BASE_DIR }}/results/summary.md
            if [ -d "${{ env.BASE_DIR }}/results/$FUZZER" ]; then
              find "${{ env.BASE_DIR }}/results/$FUZZER" -type f -name "*.json" -exec cat {} \; | \
                jq -r '. | select(.type=="finding") | "- " + .description' >> ${{ env.BASE_DIR }}/results/summary.md || true
            fi
          done
        shell: bash

      - name: Upload Summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fuzzing-summary
          path: ${{ env.BASE_DIR }}/results/summary.md
          retention-days: 14
