name: WuppieFuzz Build and Fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_fuzz:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get WuppieFuzz commit hash
        id: wuppiefuzz_commit
        run: |
          git ls-remote https://github.com/TNO-S3/WuppieFuzz.git HEAD | awk '{print $1}' > wuppiefuzz_commit.txt
          echo "commit_hash=$(cat wuppiefuzz_commit.txt)" >> $GITHUB_ENV

      - name: Clone WuppieFuzz repository
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v4.1.1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            WuppieFuzz/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('WuppieFuzz/Cargo.lock') }}-${{ env.commit_hash }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run services with Docker Compose
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          docker network create wuppycicd_network || true
          docker-compose up -d --build

      - name: Wait for services to start
        run: sleep 15

      - name: Test API Connectivity
        run: |
          curl -I http://localhost:3001

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies for WuppieFuzz
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release
          cd ..

      - name: Add WuppieFuzz to PATH
        run: |
          echo "${{ github.workspace }}/WuppieFuzz/target/release" >> $GITHUB_PATH

      - name: Generate initial corpus
        run: wuppiefuzz output-corpus --openapi-spec=openapi.yaml corpus_directory

      - name: Run WuppieFuzz
        env:
          RUST_BACKTRACE: 1
        run: |
          wuppiefuzz fuzz --report=true --log-level=info --initial-corpus=corpus_directory \
          --timeout=60 openapi.yaml

      - name: List reports directory
        run: ls -la reports/

      - name: Upload WuppieFuzz report
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-report
          path: reports/

      - name: Upload report.db
        uses: actions/upload-artifact@v4
        with:
          name: report-db
          path: reports/report.db

      - name: Stop and remove Docker containers
        if: always()
        run: docker-compose down

  grafana_setup:
    runs-on: self-hosted
    needs: build_and_fuzz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Grafana
        run: |
          docker network create wuppycicd_network || true
          cat <<EOF > docker-compose-grafana.yml
          version: '3'
          services:
            grafana:
              image: grafana/grafana:latest
              ports:
                - "3000:3000"
              networks:
                - wuppycicd_network
              volumes:
                - ./reports/report.db:/var/lib/grafana/data/report.db
                - ./grafana.ini:/etc/grafana/grafana.ini
              environment:
                - GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }}
                - GF_INSTALL_PLUGINS=grafana-sqlite-datasource
          networks:
            wuppycicd_network:
              external: true
          EOF
          docker-compose -f docker-compose-grafana.yml up -d

      - name: Wait for Grafana to start
        run: sleep 15

      - name: Provision Grafana dashboards
        run: |
          docker cp provisioning/dashboards.yaml grafana:/etc/grafana/provisioning/dashboards/
          docker cp provisioning/datasources.yaml grafana:/etc/grafana/provisioning/datasources/

      - name: List Grafana provisioning directory
        run: docker exec grafana ls -la /etc/grafana/provisioning/
