name: Build and Fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare_docker_network:
    runs-on: self-hosted
    steps:
      - name: Create Docker Network
        run: docker network create cicd_network || true

  prepare_vampi:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
              
      - name: Build VamPI Images
        run: |
          cd VAmPI-master
          docker-compose -f docker-compose.yaml build
      - name: Upload VamPI Files
        uses: actions/upload-artifact@v4
        with:
          name: VAmPI-master
          path: |
            VAmPI-master/
            !VAmPI-master/node_modules/

  prepare_wuppiefuzz:
    runs-on: self-hosted
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
      - name: Checkout WuppieFuzz Repository
        uses: actions/checkout@v4
        with:
          repository: TNO-S3/WuppieFuzz
          path: wuppiefuzz

      - name: Cache WuppieFuzz Build
        id: cache-wuppiefuzz-build
        uses: actions/cache@v4
        with:
          path: wuppiefuzz/target
          key: wuppiefuzz-target-${{ hashFiles('wuppiefuzz/Cargo.lock') }}

      - name: Build WuppieFuzz
        if: steps.cache-wuppiefuzz-build.outputs.cache-hit != 'true'
        run: |
          cd wuppiefuzz
          cargo build --release
      - name: Upload WuppieFuzz Binary
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-binary
          path: wuppiefuzz/target/release/wuppiefuzz

  run_restler:
    runs-on: self-hosted
    needs: [prepare_vampi, prepare_docker_network]
    steps:
      - name: Create Workspace
        run: mkdir -p workspace

      - name: Download VamPI Artifact
        uses: actions/download-artifact@v4
        with:
          name: VAmPI-master
          path: workspace/VAmPI-master

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: workspace/repo

      - name: Copy RESTler Files
        run: |
          cp -r workspace/repo/restler/restler_config workspace/
          cp workspace/repo/restler/docker-compose-restler.yml workspace/
          cp workspace/repo/restler/Dockerfile.restler workspace/
          # Remove the following line to avoid conflict with Docker volume mount
          # cp workspace/VAmPI-master/openapi_specs/openapi3.yml workspace/openapi3.yml
          echo "Files in workspace:"
          ls -la workspace/
      
      - name: Verify openapi3.yml
        run: |
          if [ ! -f "workspace/VAmPI-master/openapi_specs/openapi3.yml" ]; then
            echo "openapi3.yml is missing or not a file."
            ls -la workspace/VAmPI-master/openapi_specs/
            exit 1
          fi
          echo "openapi3.yml exists and is a file."
      
      - name: Start VamPI RESTler Instance
        run: |
          cd workspace/restler
          docker-compose -f docker-compose-restler.yml up -d restler
      
      - name: Wait for VamPI RESTler
        run: |
          echo "Waiting for VamPI RESTler instance..."
          until curl -s http://localhost:5003/ > /dev/null; do
            echo "VamPI not ready. Retrying in 5 seconds..."
            sleep 5
          done
          echo "VamPI RESTler instance is up!"
      
      - name: Run RESTler
        run: |
          cd workspace/restler
          docker-compose -f docker-compose-restler.yml up --build
      - name: Upload RESTler Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restler-results
          path: workspace/restler/output/**
  
      - name: Cleanup
        if: always()
        run: |
          cd workspace/restler
          docker-compose -f docker-compose-restler.yml down
          rm -rf workspace

  run_wuppiefuzz:
    runs-on: self-hosted
    needs: [prepare_wuppiefuzz, prepare_vampi, prepare_docker_network]
    steps:
      - name: Create Workspace
        run: mkdir -p wuppiefuzz_workspace

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: VAmPI-master
          path: workspace/vampi-api
      - name: Download WuppieFuzz Binary
        uses: actions/download-artifact@v4
        with:
          name: wuppiefuzz-binary
          path: wuppiefuzz_workspace/wuppiefuzz-binary

      - name: Setup Environment
        run: |
          chmod +x wuppiefuzz_workspace/wuppiefuzz-binary/wuppiefuzz
          mv wuppiefuzz_workspace/wuppiefuzz-binary/wuppiefuzz wuppiefuzz_workspace/
      - name: Start VamPI Instance
        run: |
          cd workspace/vampi-api/VAmPI-master
          docker-compose -f docker-compose.yaml up -d vampi-vulnerable-wuppiefuzz
      - name: Wait for VamPI
        run: |
          echo "Waiting for VamPI WuppieFuzz instance..."
          until curl -s http://localhost:5002/ > /dev/null; do
            echo "VamPI not ready. Retrying in 5 seconds..."
            sleep 5
          done
          echo "VamPI WuppieFuzz instance is up!"
      - name: Run WuppieFuzz
        run: |
          cd wuppiefuzz_workspace
          mkdir -p reports
          ./wuppiefuzz output-corpus \
            --openapi-spec=workspace/vampi-api/VAmPI-master/openapi_specs/openapi3.yml \
            corpus_directory
          ./wuppiefuzz fuzz \
            --report=true \
            --log-level=info \
            --initial-corpus=corpus_directory \
            --timeout=60 \
            --base-url=http://localhost:5002 \
            workspace/vampi-api/VAmPI-master/openapi_specs/openapi3.yml
      - name: Upload WuppieFuzz Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-results
          path: wuppiefuzz_workspace/reports/
  
      - name: Cleanup
        if: always()
        run: |
          cd workspace/vampi-api/VAmPI-master
          docker-compose -f docker-compose.yaml down
          rm -rf wuppiefuzz_workspace

  summarize_results:
    runs-on: self-hosted
    needs: [run_wuppiefuzz, run_restler]
    steps:
      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          name: '**'
          path: all_results

      - name: Create Summary
        run: |
          echo "# Fuzzing Results Summary" > summary.md
          echo "## WuppieFuzz Results" >> summary.md
          if [ -d "all_results/wuppiefuzz-results" ]; then
            issues_found=$(grep -c 'Issue' all_results/wuppiefuzz-results/report.txt || echo "0")
            echo "Number of issues found: $issues_found" >> summary.md
            if [ -f "all_results/wuppiefuzz-results/report.txt" ]; then
              echo "### Detailed Findings" >> summary.md
              cat "all_results/wuppiefuzz-results/report.txt" >> summary.md
            fi
          else
            echo "No WuppieFuzz results found" >> summary.md
          fi
          echo "## RESTler Results" >> summary.md
          if [ -d "all_results/restler-results" ]; then
            bugs_found=$(grep -c 'Bug' all_results/restler-results/bug_buckets/BugBuckets.txt || echo "0")
            echo "Number of bugs found: $bugs_found" >> summary.md
            if [ -f "all_results/restler-results/bug_buckets/BugBuckets.txt" ]; then
              echo "### Detailed Findings" >> summary.md
              cat "all_results/restler-results/bug_buckets/BugBuckets.txt" >> summary.md
            fi
          else
            echo "No RESTler results found" >> summary.md
          fi
      - name: Upload Summary
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-summary
          path: summary.md

      - name: Final Cleanup
        if: always()
        run: |
          docker container prune -f
          docker network prune -f
