name: WuppieFuzz Build and Fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_fuzz:
    runs-on: self-hosted

    steps:
      - name: Clean up Docker networks and containers
        if: always()
        run: |
          docker-compose down --remove-orphans
          docker network rm wuppycicd_network || true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false  # Prevents the action from failing due to permission issues

      - name: Manually clean untracked files
        run: |
          sudo rm -rf reports/
          git clean -ffdx

      - name: Get WuppieFuzz commit hash
        id: wuppiefuzz_commit
        run: |
          git ls-remote https://github.com/TNO-S3/WuppieFuzz.git HEAD | awk '{print $1}' > wuppiefuzz_commit.txt
          echo "commit_hash=$(cat wuppiefuzz_commit.txt)" >> $GITHUB_ENV

      - name: Clone WuppieFuzz repository
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v4.1.1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            WuppieFuzz/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('WuppieFuzz/Cargo.lock') }}-${{ env.commit_hash }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run services with Docker Compose
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          # Check if the network exists before creating it
          docker network inspect wuppycicd_network >/dev/null 2>&1 || docker network create wuppycicd_network
          docker-compose up -d --build

      - name: Wait for services to start
        run: sleep 15

      - name: Test API Connectivity
        run: |
          curl -I http://localhost:3001

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies for WuppieFuzz
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release
          cd ..

      - name: Add WuppieFuzz to PATH
        run: |
          echo "${{ github.workspace }}/WuppieFuzz/target/release" >> $GITHUB_PATH

      - name: Generate initial corpus
        run: wuppiefuzz output-corpus --openapi-spec=openapi.yaml corpus_directory

      - name: Run WuppieFuzz
        env:
          RUST_BACKTRACE: 1
        run: |
          wuppiefuzz fuzz --report=true --log-level=info --initial-corpus=corpus_directory \
          --timeout=60 openapi.yaml

      - name: Copy report.db to reports/grafana/
        run: |
          mkdir -p reports/grafana
          REPORT_DB_PATH=$(find reports/ -name report.db)
          cp "$REPORT_DB_PATH" reports/grafana/

      - name: Verify report.db exists
        run: ls -la reports/grafana/report.db

      - name: Upload WuppieFuzz report
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-report
          path: reports/

      - name: Upload report.db
        uses: actions/upload-artifact@v4
        with:
          name: report-db
          path: reports/grafana/report.db

      - name: Stop and remove Docker containers
        if: always()
        run: |
          docker-compose down --remove-orphans
          docker network rm wuppycicd_network || true

      - name: Adjust permissions of workspace
        if: always()
        run: |
          sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE
          sudo chmod -R u+rwX $GITHUB_WORKSPACE

  grafana_setup:
    runs-on: self-hosted
    needs: build_and_fuzz

    steps:
      - name: Clean up Docker networks and containers
        if: always()
        run: |
          docker-compose -f docker-compose-grafana.yml down --remove-orphans
          docker network rm wuppycicd_network || true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false  # Prevents the action from failing due to permission issues

      - name: Manually clean untracked files
        run: |
          sudo rm -rf reports/
          git clean -ffdx

      - name: Download report.db
        uses: actions/download-artifact@v4
        with:
          name: report-db
          path: report-db  # Downloads artifact into the 'report-db' directory

      - name: Move report.db to reports/grafana directory
        run: |
          mkdir -p reports/grafana
          if [ -f report-db/report.db ]; then
            mv report-db/report.db reports/grafana/report.db
          else
            echo "Error: report-db/report.db not found."
            exit 1
          fi

      - name: Get UID and GID
        id: get_uid_gid
        run: |
          echo "MY_UID=$(id -u)" >> $GITHUB_ENV
          echo "MY_GID=$(id -g)" >> $GITHUB_ENV

      - name: Set up Grafana
        env:
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
          MY_UID: ${{ env.MY_UID }}
          MY_GID: ${{ env.MY_GID }}
        run: |
          # Check if the network exists before creating it
          docker network inspect wuppycicd_network >/dev/null 2>&1 || docker network create wuppycicd_network

          # Start the Grafana container using the docker-compose-grafana.yml from the repository
          docker-compose -f docker-compose-grafana.yml up -d

      - name: Wait for Grafana to start
        run: sleep 15

      - name: List Grafana provisioning directory
        run: docker exec grafana-dashboard ls -la /etc/grafana/provisioning/

      - name: Stop and remove Grafana container
        if: always()
        run: |
          docker-compose -f docker-compose-grafana.yml down --remove-orphans
          docker network rm wuppycicd_network || true

      - name: Adjust permissions of workspace
        if: always()
        run: |
          sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE
          sudo chmod -R u+rwX $GITHUB_WORKSPACE
