name: Build and Fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    steps:
      - name: Clean up Docker resources
        if: always()
        run: |
          docker container prune -f
          docker network prune -f
          docker network rm cicd_network || true

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Checkout Main Repository
        uses: actions/checkout@v4

  prepare_wuppiefuzz:
    runs-on: self-hosted
    steps:
      - name: Checkout WuppieFuzz Repository
        uses: actions/checkout@v4
        with:
          repository: TNO-S3/WuppieFuzz
          path: wuppiefuzz

      - name: Cache WuppieFuzz Build
        id: cache-wuppiefuzz-build
        uses: actions/cache@v4
        with:
          path: wuppiefuzz/target
          key: wuppiefuzz-target-${{ hashFiles('wuppiefuzz/Cargo.lock') }}

      - name: Setup Rust and Build WuppieFuzz
        if: steps.cache-wuppiefuzz-build.outputs.cache-hit != 'true'
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          cd wuppiefuzz
          cargo build --release

      - name: Upload WuppieFuzz Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-build
          path: wuppiefuzz/target

  prepare_restler:
    runs-on: self-hosted
    steps:
      - name: Clone RESTler Repository
        run: |
          git clone https://github.com/microsoft/restler-fuzzer.git restler

      - name: Build RESTler Docker Image
        run: |
          cd restler
          docker build -t restler:latest -f ./Dockerfile .

      - name: Save RESTler Docker Image
        run: |
          docker save restler:latest -o restler_image.tar

      - name: Upload RESTler Image
        uses: actions/upload-artifact@v4
        with:
          name: restler-image
          path: restler_image.tar

  prepare_api:
    runs-on: self-hosted
    steps:
      - name: Checkout API Repository
        uses: actions/checkout@v4
        with:
          repository: silv3rshi3ld/WuppieFuzzCICD
          path: api

      - name: Upload API
        uses: actions/upload-artifact@v4
        with:
          name: vulnerable-api
          path: api/

  run_wuppiefuzz:
    runs-on: self-hosted
    needs: [prepare_wuppiefuzz, prepare_api]
    strategy:
      fail-fast: false
    steps:
      - name: Setup Docker Network
        run: |
          docker network create --driver bridge cicd_network || true

      - name: Create Workspace
        run: |
          mkdir -p wuppiefuzz_workspace
          cd wuppiefuzz_workspace
          mkdir -p wuppiefuzz api

      - name: Download WuppieFuzz Build
        uses: actions/download-artifact@v4
        with:
          name: wuppiefuzz-build
          path: wuppiefuzz_workspace/wuppiefuzz

      - name: Download API
        uses: actions/download-artifact@v4
        with:
          name: vulnerable-api
          path: wuppiefuzz_workspace/api

      - name: Start API Service
        run: |
          cd wuppiefuzz_workspace/api
          docker-compose -f docker-compose.base.yml up -d --build

      - name: Wait for API
        run: |
          echo "Waiting for API to become available..."
          until curl -s http://localhost:3001 > /dev/null; do
            echo "API not ready. Retrying in 5 seconds..."
            sleep 5
          done
          echo "API is up!"

      - name: Run WuppieFuzz
        run: |
          cd wuppiefuzz_workspace
          chmod +x wuppiefuzz/target/release/wuppiefuzz
          # Generate initial corpus
          ./wuppiefuzz/target/release/wuppiefuzz output-corpus --openapi-spec=api/openapi.yaml corpus_directory
          # Run fuzzing
          ./wuppiefuzz/target/release/wuppiefuzz fuzz \
            --report=true \
            --log-level=info \
            --initial-corpus=corpus_directory \
            --timeout=60 \
            api/openapi.yaml

      - name: Upload WuppieFuzz Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-results-${{ github.run_id }}
          path: wuppiefuzz_workspace/wuppiefuzz/reports/

      - name: Cleanup WuppieFuzz
        if: always()
        run: |
          cd wuppiefuzz_workspace/api
          docker-compose -f docker-compose.base.yml down --remove-orphans || true
          cd ../../
          rm -rf wuppiefuzz_workspace

  run_restler:
    runs-on: self-hosted
    needs: [prepare_restler, prepare_api]
    strategy:
      fail-fast: false
    steps:
      - name: Setup Docker Network
        run: |
          docker network create --driver bridge cicd_network || true

      - name: Create Workspace
        run: |
          mkdir -p restler_workspace
          cd restler_workspace
          mkdir -p api

      - name: Download RESTler Image
        uses: actions/download-artifact@v4
        with:
          name: restler-image
          path: restler_workspace

      - name: Load RESTler Docker Image
        run: |
          docker load -i restler_workspace/restler_image.tar

      - name: Download API
        uses: actions/download-artifact@v4
        with:
          name: vulnerable-api
          path: restler_workspace/api

      - name: Start API Service
        run: |
          cd restler_workspace/api
          docker-compose -f docker-compose.base.yml up -d --build

      - name: Wait for API
        run: |
          echo "Waiting for API to become available..."
          until curl -s http://localhost:3001 > /dev/null; do
            echo "API not ready. Retrying in 5 seconds..."
            sleep 5
          done
          echo "API is up!"

      - name: Run RESTler
        run: |
          cd restler_workspace
          cp api/openapi.yaml ./openapi.yaml
          docker run --rm --network host \
            -v "$(pwd)":/workspace \
            restler:latest \
            /bin/bash -c "restler compile --api_spec /workspace/openapi.yaml && \
                          restler fuzz --time_budget 1 --output_dir /workspace/restler_output"

      - name: Upload RESTler Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restler-results-${{ github.run_id }}
          path: restler_workspace/restler_output/

      - name: Cleanup RESTler
        if: always()
        run: |
          cd restler_workspace/api
          docker-compose -f docker-compose.base.yml down --remove-orphans || true
          cd ../../
          rm -rf restler_workspace

  summarize_results:
    runs-on: self-hosted
    needs: [run_wuppiefuzz, run_restler]
    if: always()
    steps:
      - name: Final Cleanup
        run: |
          docker container prune -f
          docker network prune -f

      - name: Download Results
        uses: actions/download-artifact@v4
        with:
          name: '**'
          path: all_results

      - name: Create Summary
        run: |
          echo "# Fuzzing Results Summary" > summary.md
          echo "## WuppieFuzz Results" >> summary.md
          if [ -d "all_results/wuppiefuzz-results-${{ github.run_id }}" ]; then
            issues_found=$(grep -c 'Issue' all_results/wuppiefuzz-results-${{ github.run_id }}/report.txt || echo "0")
            echo "Number of issues found: $issues_found" >> summary.md
            if [ -f "all_results/wuppiefuzz-results-${{ github.run_id }}/report.txt" ]; then
              echo "### Detailed Findings" >> summary.md
              cat "all_results/wuppiefuzz-results-${{ github.run_id }}/report.txt" >> summary.md
            fi
          else
            echo "No WuppieFuzz results found" >> summary.md
          fi
          
          echo "## RESTler Results" >> summary.md
          if [ -d "all_results/restler-results-${{ github.run_id }}" ]; then
            bugs_found=$(grep -c 'Bug' all_results/restler-results-${{ github.run_id }}/bug_buckets/BugBuckets.txt || echo "0")
            echo "Number of bugs found: $bugs_found" >> summary.md
            if [ -f "all_results/restler-results-${{ github.run_id }}/bug_buckets/BugBuckets.txt" ]; then
              echo "### Detailed Findings" >> summary.md
              cat "all_results/restler-results-${{ github.run_id }}/bug_buckets/BugBuckets.txt" >> summary.md
            fi
          else
            echo "No RESTler results found" >> summary.md
          fi

      - name: Upload Summary
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-summary
          path: summary.md
