name: Build and Fuzz

on:
  push:
    branches:
      - working
  pull_request:
    branches: 
      - working

env:
  VAMPI_RESTLER_PORT: 5003
  VAMPI_WUPPIEFUZZ_PORT: 5002
  VAMPI_EVOMASTER_PORT: 5000
  BASE_DIR: ${{ github.workspace }}
  NETWORK_SUFFIX: ${{ github.run_id }} # Unique network identifier

jobs:
  setup_vampi:
    runs-on: manager-runner
    steps:
      - uses: actions/checkout@v4
      - name: Start VAmPI instances
        working-directory: ${{ env.BASE_DIR }}/services/vampi
        run: |
          docker-compose -f docker-compose.vampi.yml up -d \
            vampi-evomaster \
            vampi-restler \ 
            vampi-wuppiefuzz

  run_restler:
    runs-on: manager-runner
    needs: setup_vampi
    steps:
      - uses: actions/checkout@v4
      - name: Run RESTler
        working-directory: ${{ env.BASE_DIR }}/services/restler
        env:
          TARGET_HOST: vampi-restler
          TARGET_PORT: ${{ env.VAMPI_RESTLER_PORT }}
        run: |
          docker-compose -f docker-compose.restler.yml up --build
      - uses: actions/upload-artifact@v4
        with:
          name: restler-results
          path: ${{ env.BASE_DIR }}/workspace/restler/output

  # Similar updates for run_wuppiefuzz and run_evomaster jobs...

  post_process:
    runs-on: manager-runner
    needs: [run_restler, run_wuppiefuzz, run_evomaster]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: all_results
      - name: Generate summary
        run: |
          echo "Security Test Results Summary" > report.md
          echo "============================" >> report.md
          
          # RESTler results
          echo "### RESTler Findings" >> report.md
          find all_results/restler-results -name 'bug_buckets.json' -exec jq '.bugs[].message' {} + >> report.md || echo "No RESTler findings" >> report.md
          
          # WuppieFuzz results
          echo "### WuppieFuzz Findings" >> report.md
          find all_results/wuppiefuzz-results -name '*.json' -exec jq '.vulnerabilities[]?.description' {} + >> report.md || echo "No WuppieFuzz findings" >> report.md
          
          # EvoMaster results
          echo "### EvoMaster Findings" >> report.md
          find all_results/evomaster-results -name '*.txt' -exec cat {} + >> report.md || echo "No EvoMaster findings" >> report.md
          
          cat report.md
      - uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report.md

  cleanup:
    runs-on: manager-runner
    needs: post_process
    if: always()
    steps:
      - name: Remove containers and networks
        run: |
          docker-compose -f services/vampi/docker-compose.vampi.yml down -v
          docker-compose -f services/restler/docker-compose.restler.yml down -v
          docker-compose -f services/wuppiefuzz/docker-compose.wuppie.yml down -v
          docker system prune -af
          docker volume prune -f
