name: WuppieFuzz Build and Fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_fuzz:
    runs-on: self-hosted

    steps:
      - name: Clean up Docker networks and containers
        if: always()
        run: |
          docker-compose down --remove-orphans
          docker network rm wuppycicd_network || true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Manually clean untracked files
        run: |
          sudo rm -rf reports/
          git clean -ffdx

      - name: Get WuppieFuzz commit hash
        id: wuppiefuzz_commit
        run: |
          git ls-remote https://github.com/TNO-S3/WuppieFuzz.git HEAD | awk '{print $1}' > wuppiefuzz_commit.txt
          echo "commit_hash=$(cat wuppiefuzz_commit.txt)" >> $GITHUB_ENV

      - name: Clone WuppieFuzz repository
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            WuppieFuzz/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('WuppieFuzz/Cargo.lock') }}-${{ env.commit_hash }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run services with Docker Compose
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          docker network inspect wuppycicd_network >/dev/null 2>&1 || docker network create wuppycicd_network
          docker-compose up -d --build

      - name: Wait for services to start
        run: sleep 15

      - name: Test API Connectivity
        run: curl -I http://localhost:3001

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies for WuppieFuzz
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release
          cd ..

      - name: Add WuppieFuzz to PATH
        run: |
          echo "${{ github.workspace }}/WuppieFuzz/target/release" >> $GITHUB_PATH

      - name: Generate initial corpus
        run: wuppiefuzz output-corpus --openapi-spec=openapi.yaml corpus_directory

      - name: Run WuppieFuzz
        env:
          RUST_BACKTRACE: 1
        run: |
          wuppiefuzz fuzz --report=true --log-level=info --initial-corpus=corpus_directory --timeout=1800 openapi.yaml

      - name: Copy report.db to reports/grafana
        run: |
          mkdir -p reports/grafana
          REPORT_DB_PATH=$(find reports/ -name report.db)
          cp "$REPORT_DB_PATH" reports/grafana/

      - name: Verify report.db exists
        run: ls -la reports/grafana/report.db

      - name: Upload report.db
        uses: actions/upload-artifact@v4
        with:
          name: report-db
          path: reports/grafana/report.db

      - name: Adjust permissions of workspace
        if: always()
        run: |
          sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE
          sudo chmod -R u+rwX $GITHUB_WORKSPACE

  grafana_setup:
    runs-on: self-hosted
    needs: build_and_fuzz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Download report.db
        uses: actions/download-artifact@v4
        with:
          name: report-db
          path: reports/grafana

      - name: Verify report.db exists after download
        run: ls -la reports/grafana/

      - name: Prepare provisioning files
        run: |
          mkdir -p provisioning/dashboards
          mkdir -p provisioning/datasources
          cp WuppieFuzz-dashboard/provisioning/dashboards.yaml provisioning/dashboards/
          cp WuppieFuzz-dashboard/provisioning/datasources.yaml provisioning/datasources/
          cp WuppieFuzz-dashboard/grafana.ini ./grafana.ini
          cp -r WuppieFuzz-dashboard/dashboards/*.json provisioning/dashboards/

      - name: Adjust permissions for Grafana files
        run: |
          sudo chown -R 472:472 reports/grafana
          sudo chown -R 472:472 provisioning
          sudo chown 472:472 grafana.ini

      - name: Build custom Grafana image with SQLite plugin
        run: |
          echo 'FROM grafana/grafana-enterprise
          RUN grafana-cli plugins install frser-sqlite-datasource
          ' > Dockerfile
          docker build -t custom-grafana .

      - name: Create docker-compose-grafana.yml
        run: |
          echo 'version: "3.8"

          services:
            grafana-dashboard:
              image: custom-grafana
              container_name: grafana-dashboard
              ports:
                - "3000:3000"
              environment:
                - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
              volumes:
                - type: bind
                  source: ${GITHUB_WORKSPACE}/reports/grafana/report.db
                  target: /var/lib/grafana/datasources/report.db
                - type: bind
                  source: ${GITHUB_WORKSPACE}/provisioning/dashboards
                  target: /var/lib/grafana/dashboards
                - type: bind
                  source: ${GITHUB_WORKSPACE}/grafana.ini
                  target: /etc/grafana/grafana.ini
                - type: bind
                  source: ${GITHUB_WORKSPACE}/provisioning
                  target: /etc/grafana/provisioning
              networks:
                default:
                  name: wuppycicd_network

          networks:
            default:
              external: true
          ' > docker-compose-grafana.yml

      - name: Set up Grafana
        env:
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          docker network inspect wuppycicd_network >/dev/null 2>&1 || docker network create wuppycicd_network
          docker-compose -f docker-compose-grafana.yml up -d
          docker ps -a

      - name: Wait for Grafana to start
        run: |
          for i in {1..10}; do
            if docker inspect -f '{{.State.Running}}' grafana-dashboard | grep true; then
              echo "Grafana is running"
              break
            else
              echo "Waiting for Grafana to start..."
              sleep 10
            fi
          done

      - name: Output Grafana logs
        run: docker logs grafana-dashboard

      - name: Adjust permissions of workspace
        if: always()
        run: |
          sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE
          sudo chmod -R u+rwX $GITHUB_WORKSPACE
