name: WuppieFuzz Build and Fuzz

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_docker:
    runs-on: self-hosted
    outputs:
      docker_cache_key: ${{ steps.set_cache_key.outputs.docker_cache_key }}
    steps:
      - name: Clean up Docker networks and containers
        if: always()
        run: |
          docker-compose down --remove-orphans
          docker network rm wuppycicd_network || true

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Cache Key
        id: set_cache_key
        run: echo "::set-output name=docker_cache_key::docker-cache-${{ github.sha }}"

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ steps.set_cache_key.outputs.docker_cache_key }}
          restore-keys: |
            docker-cache-

  checkout_repos:
    runs-on: self-hosted
    needs: setup_docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Manually clean untracked files
        run: |
          sudo rm -rf reports/
          git clean -ffdx

      - name: Get WuppieFuzz commit hash
        id: wuppiefuzz_commit
        run: |
          git ls-remote https://github.com/TNO-S3/WuppieFuzz.git HEAD | awk '{print $1}' > wuppiefuzz_commit.txt
          echo "commit_hash=$(cat wuppiefuzz_commit.txt)" >> $GITHUB_ENV

      - name: Clone WuppieFuzz repository
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

  cache_dependencies:
    runs-on: self-hosted
    needs: checkout_repos
    steps:
      - name: Restore Rust and Git caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            WuppieFuzz/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('WuppieFuzz/Cargo.lock') }}-${{ env.commit_hash }}
          restore-keys: |
            ${{ runner.os }}-cargo-

  build_and_run:
    runs-on: self-hosted
    needs: [setup_docker, cache_dependencies]
    steps:
      - name: Restore Docker Buildx Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ needs.setup_docker.outputs.docker_cache_key }}
          restore-keys: |
            docker-cache-

      - name: Build and run services with Docker Compose
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          docker network inspect wuppycicd_network >/dev/null 2>&1 || docker network create wuppycicd_network
          docker-compose up -d --build

      - name: Export Docker Buildx Cache
        if: success()
        run: |
          docker buildx build --cache-to=type=local,dest=/tmp/.buildx-cache --cache-import=type=local,src=/tmp/.buildx-cache --pull --push

  test_connectivity:
    runs-on: self-hosted
    needs: build_and_run
    steps:
      - name: Wait for services to start
        run: sleep 15

      - name: Test API Connectivity
        run: curl -I http://localhost:3001

  run_fuzz:
    runs-on: self-hosted
    needs: test_connectivity
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies for WuppieFuzz
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release
          cd ..

      - name: Add WuppieFuzz to PATH
        run: |
          echo "${{ github.workspace }}/WuppieFuzz/target/release" >> $GITHUB_PATH

      - name: Generate initial corpus
        run: wuppiefuzz output-corpus --openapi-spec=openapi.yaml corpus_directory

      - name: Run WuppieFuzz
        env:
          RUST_BACKTRACE: 1
        run: |
          if [ -f "login.yaml" ]; then
            wuppiefuzz fuzz --report=true --log-level=info --initial-corpus=corpus_directory --timeout=60 --authentication login.yaml openapi.yaml
          else
            wuppiefuzz fuzz --report=true --log-level=info --initial-corpus=corpus_directory --timeout=60 openapi.yaml

  finalize:
    runs-on: self-hosted
    needs: run_fuzz
    steps:
      - name: Upload report directory
        uses: actions/upload-artifact@v4
        with:
          name: report-directory
          path: reports/

      - name: Adjust permissions of workspace
        if: always()
        run: |
          sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE
          sudo chmod -R u+rwX $GITHUB_WORKSPACE

      - name: Clean up Docker networks and containers
        if: always()
        run: |
          docker-compose down --remove-orphans
          docker network rm wuppycicd_network || true

name: RESTler API Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_docker:
    runs-on: self-hosted
    outputs:
      docker_cache_key: ${{ steps.set_cache_key.outputs.docker_cache_key }}
    steps:
      - name: Clean up Docker networks and containers
        if: always()
        run: |
          docker-compose down --remove-orphans
          docker network rm restler_network || true

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Cache Key
        id: set_cache_key
        run: echo "::set-output name=docker_cache_key::$(echo "docker-cache-${{ github.sha }}" | cut -c1-32)"

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ steps.set_cache_key.outputs.docker_cache_key }}
          restore-keys: |
            docker-cache-

  checkout_repos:
    runs-on: self-hosted
    needs: setup_docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Manually clean untracked files
        run: |
          sudo rm -rf reports/
          git clean -ffdx

      - name: Get RESTler API commit hash
        id: restler_commit
        run: |
          git ls-remote https://github.com/your-org/RESTlerAPI.git HEAD | awk '{print $1}' > restler_commit.txt
          echo "commit_hash=$(cat restler_commit.txt)" >> $GITHUB_ENV

      - name: Clone RESTler API repository
        run: git clone https://github.com/your-org/RESTlerAPI.git

  build_and_run:
    runs-on: self-hosted
    needs: [setup_docker, checkout_repos]
    steps:
      - name: Restore Docker Buildx Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ needs.setup_docker.outputs.docker_cache_key }}
          restore-keys: |
            docker-cache-

      - name: Build and run services with Docker Compose
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          docker network inspect restler_network >/dev/null 2>&1 || docker network create restler_network
          docker-compose up -d --build

      - name: Export Docker Buildx Cache
        if: success()
        run: |
          docker buildx bake --push

  test_connectivity:
    runs-on: self-hosted
    needs: build_and_run
    steps:
      - name: Wait for services to start
        run: sleep 15

      - name: Test API Connectivity
        run: curl -I http://localhost:3001

