name: Fuzz VAmPI with WuppieFuzz

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Run VAmPI via Docker in vulnerable mode.
      # This pulls the Docker image from Docker Hub and sets the environment variable to ensure the vulnerable parts are active.
      - name: Start VAmPI Container (Vulnerable Mode)
        run: |
          docker run -d --name vampi -e vulnerable=1 -p 5000:5000 erev0s/vampi:latest
          # Allow time for the container to initialize
          sleep 10

      # 3. Initialize the VAmPI database.
      # VAmPI requires a call to /createdb to populate its dummy data.
      - name: Initialize VAmPI Database
        run: |
          curl -s http://localhost:5000/createdb

      # 4. Set up the Rust toolchain (required to build WuppieFuzz).
      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 5. Clone the WuppieFuzz repository.
      - name: Clone WuppieFuzz
        run: git clone https://github.com/TNO-S3/WuppieFuzz.git

      # 6. Build WuppieFuzz.
      - name: Build WuppieFuzz
        run: |
          cd WuppieFuzz
          cargo build --release

      # 7. Generate an initial corpus from the OpenAPI specification.
      # Assumes that VAmPI’s OpenAPI spec is available at openapi_specs/openapi3.yaml in your repository.
      - name: Generate Initial Corpus for Fuzzing
        run: |
          cd WuppieFuzz
          ./target/release/wuppiefuzz output-corpus --openapi-spec ../openapi_specs/openapi3.yaml corpus_directory

      # 8. Run the fuzzing campaign.
      # If your API requires authentication, you can extend this step to include an authentication file and/or custom headers.
      - name: Run WuppieFuzz Fuzzing Campaign
        run: |
          cd WuppieFuzz
          ./target/release/wuppiefuzz fuzz \
            --report \
            --log-level info \
            --initial-corpus corpus_directory \
            --timeout 60 \
            ../openapi_specs/openapi3.yaml

      # 9. Upload the generated fuzzing reports as an artifact.
      - name: Upload Fuzzing Report
        uses: actions/upload-artifact@v3
        with:
          name: fuzzing-report
          path: WuppieFuzz/reports/
