name: Build and Fuzz

on:
  push:
    branches:
      - working
  pull_request:
    branches:
      - working

env:
  VAMPI_RESTLER_PORT: 5003
  VAMPI_WUPPIEFUZZ_PORT: 5002
  VAMPI_EVOMASTER_PORT: 5000
  BASE_DIR: ${{ github.workspace }}

jobs:
  cleanup:
    runs-on: manager-runner
    steps:
      - name: Clean previous artifacts
        run: |
          sudo rm -rf "$BASE_DIR/workspace/restler/output" || true
          sudo rm -rf "$BASE_DIR/wuppiefuzz_workspace" || true
          sudo rm -rf "$BASE_DIR/workspace/evomaster" || true

  prepare_networks:
    runs-on: manager-runner
    steps:
      - name: Clean existing networks
        run: |
          for net in wuppiefuzz_network evomaster_network restler_network; do
            docker network rm $net || true
          done

      - name: Create dedicated networks
        run: |
          docker network create --subnet=10.10.0.0/24 wuppiefuzz_network
          docker network create --subnet=10.20.0.0/24 evomaster_network
          docker network create --subnet=10.30.0.0/24 restler_network

  setup_vampi:
    runs-on: manager-runner
    needs: prepare_networks
    steps:
      - uses: actions/checkout@v4
      - name: Start VAmPI instances
        working-directory: ${{ env.BASE_DIR }}/services/vampi
        run: |
          docker-compose -f docker-compose.vampi.yml up -d \
            vampi-evomaster \
            vampi-restler \
            vampi-wuppiefuzz

  run_restler:
    runs-on: manager-runner
    needs: [setup_vampi, prepare_networks]
    steps:
      - uses: actions/checkout@v4
      - name: Run RESTler
        working-directory: ${{ env.BASE_DIR }}/services/restler
        env:
          TARGET_HOST: vampi-restler
          TARGET_PORT: ${{ env.VAMPI_RESTLER_PORT }}
        run: |
          docker-compose -f docker-compose.restler.yml up --build
      - uses: actions/upload-artifact@v4
        with:
          name: restler-results
          path: ${{ env.BASE_DIR }}/workspace/restler/output

  run_wuppiefuzz:
    runs-on: manager-runner
    needs: [setup_vampi, prepare_networks]
    steps:
      - uses: actions/checkout@v4
      - name: Build WuppieFuzz
        run: |
          mkdir -p ${{ env.BASE_DIR }}/wuppiefuzz_bin
          docker build -t wuppiefuzz-builder -f ${{ env.BASE_DIR }}/services/wuppiefuzz/Dockerfile.wuppiefuzz .
          docker create -it --name wuppie_temp wuppiefuzz-builder
          docker cp wuppie_temp:/app/wuppiefuzz ${{ env.BASE_DIR }}/wuppiefuzz_bin/
          docker rm wuppie_temp

      - name: Execute WuppieFuzz
        working-directory: ${{ env.BASE_DIR }}/services/wuppiefuzz
        run: |
          docker-compose -f docker-compose.wuppiefuzz.yml up --build
      - uses: actions/upload-artifact@v4
        with:
          name: wuppiefuzz-results
          path: ${{ env.BASE_DIR }}/wuppiefuzz_workspace/reports

  run_evomaster:
    runs-on: manager-runner
    needs: [setup_vampi, prepare_networks]
    steps:
      - uses: actions/checkout@v4
      - name: Build EvoMaster
        working-directory: ${{ env.BASE_DIR }}/services/evomaster
        run: docker-compose -f docker-compose.evomaster.yml build

      - name: Run EvoMaster
        working-directory: ${{ env.BASE_DIR }}/services/evomaster
        run: |
          docker-compose -f docker-compose.evomaster.yml up --build
      - uses: actions/upload-artifact@v4
        with:
          name: evomaster-results
          path: ${{ env.BASE_DIR }}/workspace/evomaster/results

  post_process:
    runs-on: manager-runner
    needs: [run_restler, run_wuppiefuzz, run_evomaster]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: all_results
      - name: Generate summary
        run: |
          echo "Security Test Results Summary" > report.md
          echo "============================" >> report.md
          
          # RESTler results
          echo "### RESTler Findings" >> report.md
          find all_results/restler-results -name 'bug_buckets.json' -exec jq '.bugs[].message' {} + >> report.md || echo "No RESTler findings" >> report.md
          
          # WuppieFuzz results
          echo "### WuppieFuzz Findings" >> report.md
          find all_results/wuppiefuzz-results -name '*.json' -exec jq '.vulnerabilities[]?.description' {} + >> report.md || echo "No WuppieFuzz findings" >> report.md
          
          # EvoMaster results
          echo "### EvoMaster Findings" >> report.md
          find all_results/evomaster-results -name '*.txt' -exec cat {} + >> report.md || echo "No EvoMaster findings" >> report.md
          
          cat report.md
      - uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report.md

  cleanup_final:
    runs-on: manager-runner
    needs: post_process
    if: always()
    steps:
      - name: Remove networks
        run: |
          for net in wuppiefuzz_network evomaster_network restler_network; do
            docker network rm $net || true
          done
      - name: Prune system
        run: |
          docker system prune -af
          docker volume prune -f
